var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var h=function(){};h.prototype=a;return new h};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},h={};try{return h.__proto__=a,h.a}catch(g){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,h){a.__proto__=h;if(a.__proto__!==h)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,h){a.prototype=$jscomp.objectCreate(h.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var g=$jscomp.setPrototypeOf;g(a,h)}else for(g in h)if("prototype"!=g)if(Object.defineProperties){var v=Object.getOwnPropertyDescriptor(h,g);v&&Object.defineProperty(a,g,v)}else a[g]=h[g];a.superClass_=h.prototype};
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,h,g){a!=Array.prototype&&a!=Object.prototype&&(a[h]=g.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,h,g,v){if(h){g=$jscomp.global;a=a.split(".");for(v=0;v<a.length-1;v++){var x=a[v];x in g||(g[x]={});g=g[x]}a=a[a.length-1];v=g[a];h=h(v);h!=v&&null!=h&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:h})}};$jscomp.polyfill("Object.is",function(a){return a?a:function(a,g){return a===g?0!==a||1/a===1/g:a!==a&&g!==g}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,g){var h=this;h instanceof String&&(h=String(h));var x=h.length;g=g||0;for(0>g&&(g=Math.max(g+x,0));g<x;g++){var G=h[g];if(G===a||Object.is(G,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,h,g){if(null==a)throw new TypeError("The 'this' value for String.prototype."+g+" must not be null or undefined");if(h instanceof RegExp)throw new TypeError("First argument to String.prototype."+g+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,g){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,g||0)}},"es6","es3");
var _0x4e87="LnBva2kuY29t bG9jYWxob3N0 139KObtWR 6505XySddN 1187125jopCbV 913662FnvCIe 740825sNyBkZ 459327dmigPF 335606FqHNeg 770186hYUBAW some top aHR0cHM6Ly9wb2tpLmNvbS9zaXRlbG9jaw== location length href".split(" "),_0x3b7c=function(a,h){return _0x4e87[a-340]};
(function(a,h){for(var g=_0x3b7c;;)try{if(parseInt(g(349))+parseInt(g(348))+-parseInt(g(350))+parseInt(g(345))*parseInt(g(344))+-parseInt(g(346))+-parseInt(g(351))+parseInt(g(347))===h)break;else a.push(a.shift())}catch(v){a.push(a.shift())}})(_0x4e87,725092);
!function(){/*var a=_0x3b7c,h=window.location.hostname;[a(343),a(342),"LnBva2ktZ2RuLmNvbQ=="].map(function(a){return atob(a)})[a(352)](function(a){var g=_0x3b7c;return"."===a.charAt(0)?-1!==h.indexOf(a,h[g(340)]-a[g(340)]):a===h})||(window[a(355)][a(341)]=atob(a(354)),window[a(353)][a(355)]!==window[a(355)]&&(window[a(353)][a(355)]=window[a(355)]))*/}();var ad_show=!1;
function show_ad(){ad_show=!0;PokiSDK.commercialBreak().then(function(){ad_show=!1;console.log("Commercial break finished, proceeding to game")})}window.addEventListener("keydown",function(a){["ArrowDown","ArrowUp"," "].includes(a.key)&&ad_show&&a.preventDefault()});window.addEventListener("wheel",function(a){ad_show&&a.preventDefault()},{passive:!1});var Game=function(){return Phaser.Scene.call(this,"game")||this};$jscomp.inherits(Game,Phaser.Scene);
Game.prototype.create=function(){function a(a,f,b){var B=p.add.sprite(a,f,"obj"+b);p.tweens.add({targets:B,scaleY:0,scaleX:0,duration:150,ease:"Linear",onComplete:function(){B.destroy(!0,!0)}})}function h(a){for(var B=a.length,b,d;B;)d=Math.floor(Math.random()*B--),b=a[B],a[B]=a[d],a[d]=b;return a}function g(){q&&(q.clearTint(),q=null);for(var a=[],f=u.getLength(),b=u.getChildren(),d=0;10>d;d++)for(var c=0;8>c;c++)l[d][c].filled&&a.push(l[d][c].color);h(a);for(d=0;d<f;d++)c=b[d],c.color=a[d],c.setTexture("obj"+
c.color);Q();x()?setTimeout(function(){play_sound("shuffle",p)},200):(console.log("not match"),g())}function v(){var a=u.getLength(),f=u.getChildren(),b=x();if(b){E=b;for(var d=0;d<a;d++){var c=f[d];(c.pos.x===b[0].x&&c.pos.y===b[0].y||c.pos.x===b[1].x&&c.pos.y===b[1].y)&&c.setTint(5233606)}}else alert("err");setTimeout(function(){play_sound("hint",p)},200)}function x(){for(var a=u.getLength(),f=u.getChildren(),b=0;b<a;b++){var d=f[b];a:{var c=d.pos;for(var e=l[c.y][c.x].color,g=0;10>g;g++)for(var k=
0;8>k;k++)if((g!==c.y||k!==c.x)&&l[g][k].filled&&l[g][k].color===e&&R(c,{x:k,y:g})){c={x:k,y:g};break a}c=!1}if(c)return[d.pos,c]}return!1}function G(a){y="drop";for(var B=u.getLength(),b=u.getChildren(),d=0;d<B;d++){var c=b[d],e=l[c.pos.y][c.pos.x];if(0!=e.to.x||0!=e.to.y)c.pos.x+=e.to.x,c.pos.y+=e.to.y,p.tweens.add({targets:c,x:H+z.width*c.pos.x,y:I+z.height*c.pos.y,duration:200,ease:"Linear",onComplete:function(){a--;0===a&&(y="play",Q(),x()||(0<player_data.shuffle_left?(C.setVisible(!0),play_sound("nomatch",
p)):(y="gameover1",setTimeout(S,1E3))))}})}}function Q(){for(var a=0;10>a;a++)for(var f=0;8>f;f++)l[a][f].filled=!1,l[a][f].color=0,l[a][f].to=null;a=u.getLength();f=u.getChildren();for(var b=0;b<a;b++){var d=f[b];l[d.pos.y][d.pos.x].filled=!0;l[d.pos.y][d.pos.x].color=d.color}}function w(a){return Math.PI/180*a}function T(){for(var a=J.getChildren(),f=J.getLength(),b=0;b<f;b++)a[b].setVisible(!1)}function X(a){play_sound("connected",p);T();for(var f=J.getChildren(),b,d,c=0;c<a.length;c++){var e=
f[c];e.setVisible(!0);e.setPosition(H+z.width*a[c].x,I+z.height*a[c].y);0===c?d=a[c].x===a[c+1].x?a[c].y>a[c+1].y?"up":"down":a[c].x>a[c+1].x?"left":"right":c<a.length-1&&(a[c].x===a[c+1].x?a[c].y>a[c+1].y?(d="up","up"===b?e.setFrame(1):"down"!==b&&("left"===b?(e.setFrame(2),e.setRotation(w(180))):"right"===b&&(e.setFrame(2),e.setRotation(w(90))))):(d="down","up"!==b&&("down"===b?e.setFrame(1):"left"===b?(e.setFrame(2),e.setRotation(w(270))):"right"===b&&(e.setFrame(2),e.setRotation(w(0))))):a[c].x>
a[c+1].x?(d="left","up"===b?(e.setFrame(2),e.setRotation(w(0))):"down"===b?(e.setFrame(2),e.setRotation(w(90))):"left"===b&&e.setFrame(1)):(d="right","up"===b?(e.setFrame(2),e.setRotation(w(270))):"down"===b?(e.setFrame(2),e.setRotation(w(180))):"left"!==b&&"right"===b&&e.setFrame(1)));c===a.length-1&&(d=a[c].x===a[c-1].x?a[c].y>a[c-1].y?"up":"down":a[c].x>a[c-1].x?"left":"right",e.setFrame(0));0===e.frame.name?"up"===d?e.setRotation(w(270)):"down"===d?e.setRotation(w(90)):"left"===d?e.setRotation(w(180)):
"right"===d&&e.setRotation(w(0)):1===e.frame.name&&("up"===d||"down"===d?e.setRotation(w(90)):e.setRotation(w(0)));b=d}}function U(a,f){return 0<=a.x&&0<=a.y&&a.x<f[0].length&&a.y<f.length?!0:!1}function F(a,f,b,d,c){for(var e=[],g=1;10>g;g++){var k={x:f.x+a.x*g,y:f.y+a.y*g};if(U(k,d))if(d[k.y][k.x].filled){if(k.x===b.x&&k.y===b.y)return e.push(k),e;break}else if(e.push(k),c)if(1===a.x||-1===a.x){var h=F({x:0,y:-1},k,b,d);if(h){for(b=0;b<h.length;b++)e.push(h[b]);return e}if(k=F({x:0,y:1},k,b,d)){for(b=
0;b<k.length;b++)e.push(k[b]);return e}}else{if(h=F({x:-1,y:0},k,b,d)){for(b=0;b<h.length;b++)e.push(h[b]);return e}if(k=F({x:1,y:0},k,b,d)){for(b=0;b<k.length;b++)e.push(k[b]);return e}}else if(1===a.x||-1===a.x){if(K({x:0,y:1},k,b,d)){for(a=k.y+1;a<b.y+1;a++)e.push({x:k.x,y:a});return e}if(K({x:0,y:-1},k,b,d)){for(a=k.y-1;a>b.y-1;a--)e.push({x:k.x,y:a});return e}}else{if(K({x:1,y:0},k,b,d)){for(a=k.x+1;a<b.x+1;a++)e.push({x:a,y:k.y});return e}if(K({x:-1,y:0},k,b,d)){for(a=k.x-1;a>b.x-1;a--)e.push({x:a,
y:k.y});return e}}}return!1}function K(a,f,b,d){for(var c=1;10>c;c++){var e={x:f.x+a.x*c,y:f.y+a.y*c};if(U(e,d)){if(d[e.y][e.x].filled)return e.x===b.x&&e.y===b.y?!0:!1}else return!1}}function R(a,f){for(var b=JSON.parse(JSON.stringify(l)),d=0;10>d;d++)b[d].unshift({filled:!1}),b[d].push({filled:!1});d=[];for(var c=0;10>c;c++)d.push({filled:!1});b.push(d);b.unshift(d);a.x++;a.y++;f.x++;f.y++;d=[];for(c=0;4>c;c++){var e={x:-1,y:0};1===c?e={x:1,y:0}:2===c?e={x:0,y:-1}:3===c&&(e={x:0,y:1});if(e=F(e,
a,f,b,!0)){var g=[];e.unshift(a);for(var k=0;k<e.length;k++)g.push({x:e[k].x-1,y:e[k].y-1});d.push(g)}}b=null;c=999;for(e=0;e<d.length;e++)d[e].length<c&&(c=d[e].length,b=d[e]);a.x--;a.y--;f.x--;f.y--;return b}function V(){Y.setText(player_data.shuffle_left);Z.setText(player_data.hint_left)}function S(){PokiSDK.gameplayStop();play_sound("gameover",p);player_data.score>best_score&&(best_score=player_data.score,localStorage.setItem("redfoc_onet_best",best_score));for(var a=u.getLength(),f=u.getChildren(),
b=0;10>b;b++)for(var d=0;8>d;d++)if(l[b][d].filled){var c=0;a:for(;c<a;c++){var e=f[c];if(e.pos.x===d&&e.pos.y===b){e.depth=0;break a}}}y="gameover";p.add.rectangle(0,0,config.width,config.height,0).setOrigin(0).alpha=.8;p.add.text(360,400,"GAMEOVER",{fontFamily:"PoetsenOne",fontSize:65,align:"center",color:"#FFFFFF"}).setOrigin(.5);p.add.text(360,480,"SCORE: "+player_data.score,{fontFamily:"PoetsenOne",fontSize:45,align:"center",color:"#FFFFFF"}).setOrigin(.5);draw_button(360,610,"restart",p);draw_button(360,
700,"menu",p);localStorage.removeItem("redfoc_onet_array");player_data.drop_mode=0;player_data.score=0;last_array=null;localStorage.setItem("redfoc_onet_data",JSON.stringify(player_data))}function W(){var a={arr:l,data:player_data};last_array=JSON.parse(JSON.stringify(l));localStorage.setItem("redfoc_onet_array",JSON.stringify(a))}var N=this;PokiSDK.gameplayStart();this.add.sprite(0,0,"background").setOrigin(0);var y="play",n=0,p=this,E,O=!1,u=this.add.group();this.add.group();var J=this.add.group(),
q=0,z={width:80,height:77},H=(config.width-8*z.width)/2+z.width/2,I=(config.height-10*z.height)/2+z.height/2,l=Array(10),r=[],m=1,t=18+player_data.drop_mode;22<t&&(t=22);console.log("Max: "+t);for(var A=0;40>A;A++)m>t&&(m=1),r.push(m),m++;r=r.concat(r);h(r);m=0;if(last_array)for(l=last_array,r=0;10>r;r++)for(m=0;8>m;m++)l[r][m].filled&&(t=l[r][m].color,A=this.add.sprite(H+z.width*m,I+z.height*r,"obj"+t).setInteractive(),A.color=t,A.piece=!0,A.pos={x:m,y:r},u.add(A));else for(t=0;10>t;t++){A=[];for(var L=
0;8>L;L++){var P=r[m],aa={color:P,filled:!0},M=this.add.sprite(H+z.width*L,I+z.height*t,"obj"+P).setInteractive();M.color=P;M.piece=!0;M.pos={x:L,y:t};u.add(M);m++;A.push(aa)}l[t]=A}this.add.sprite(0,0,"header").setOrigin(0);this.add.sprite(config.width/2,35,"score_bar");var ba=this.add.text(config.width/2,35,String(player_data.score),{fontFamily:"robotomono",fontSize:40,align:"center",color:"#FFFFFF"}).setOrigin(.5);this.add.sprite(0,config.height,"footer").setOrigin(0,1);m=draw_button(650,40,"hint",
this);0===player_data.hint_left&&(m.alpha=.5);r=draw_button(560,40,"shuffle",this);0===player_data.shuffle_left&&(r.alpha=.5);draw_button(70,40,"home",this);t=draw_button(160,40,"sound_on",this);t.name="sound";check_audio(t);m=this.add.sprite(m.x+35,m.y+25,"circle");t=this.add.sprite(r.x+35,r.y+25,"circle");var Z=this.add.text(m.x,m.y,String(player_data.hint_left),{fontFamily:"robotomono",fontSize:30,align:"center",color:"#FFFFFF"}).setOrigin(.5),Y=this.add.text(t.x,t.y,String(player_data.shuffle_left),
{fontFamily:"robotomono",fontSize:30,align:"center",color:"#FFFFFF"}).setOrigin(.5),D=this.add.sprite(180,180,"sign");D.setDepth(100);D.setVisible(!1);var C=this.add.sprite(r.x,140,"arrow");C.setDepth(100);C.setVisible(!1);this.tweens.add({targets:D,scaleX:1.1,scaleY:1.1,ease:"Linear",duration:250,yoyo:!0,repeat:-1});this.tweens.add({targets:C,y:C.y+20,ease:"Linear",duration:250,yoyo:!0,repeat:-1});for(r=0;25>r;r++)m=this.add.sprite(80,80,"lines"),m.setDepth(100),m.setVisible(!1),J.add(m);this.input.keyboard.on("keydown",
function(a,f){O=a.key});this.input.keyboard.on("keyup",function(a,f){O=!1});this.input.on("gameobjectdown",function(h,f){if(ad_show)return!1;if("z"===O)l[f.pos.y][f.pos.x].filled=!1,f.destroy(!0,!0);else if(f.button)play_sound("click",N),N.tweens.add({targets:f,scaleX:.9,scaleY:.9,yoyo:!0,ease:"Linear",duration:100,onComplete:function(){"play"===y&&("hint"===f.name?0<player_data.hint_left&&(player_data.hint_left--,V(),v(),0===player_data.hint_left&&(f.alpha=.5)):"shuffle"===f.name?0<player_data.shuffle_left&&
(C.visible&&C.setVisible(!1),player_data.shuffle_left--,V(),g(),0===player_data.shuffle_left&&(f.alpha=.5)):"home"===f.name&&(PokiSDK.gameplayStop(),p.scene.start("menu")));"sound"===f.name?switch_audio(f):"next"===f.name?(show_ad(),p.scene.start("game")):"restart"===f.name?(show_ad(),player_data.drop_mode=0,player_data.score=0,p.scene.start("game")):"menu"===f.name&&(show_ad(),PokiSDK.gameplayStop(),p.scene.start("menu"))}},N);else if(f.piece){if(E){h=u.getLength();for(var b=u.getChildren(),d=0;d<
h;d++){var c=b[d];(c.pos.x===E[0].x&&c.pos.y===E[0].y||c.pos.x===E[1].x&&c.pos.y===E[1].y)&&c.clearTint()}E=null}q?"play"===y&&(play_sound("itemclick",p),f.pos.x!=q.pos.x||f.pos.y!=q.pos.y)&&(f.setTint(5233606),l[f.pos.y][f.pos.x].color===l[q.pos.y][q.pos.x].color?(h=R(q.pos,f.pos))?(player_data.score+=2,ba.setText(player_data.score),y="wait1",D.setVisible(!1),X(h),l[f.pos.y][f.pos.x].filled=!1,l[q.pos.y][q.pos.x].filled=!1,setTimeout(function(){y="wait";a(f.x,f.y,f.color);a(q.x,q.y,q.color);f.destroy(!0,
!0);q.destroy(!0,!0);q=null;setTimeout(function(){if(1===player_data.drop_mode)var a="down";else if(2===player_data.drop_mode)a="up";else if(3===player_data.drop_mode)a="left";else if(4===player_data.drop_mode)a="right";else if(5===player_data.drop_mode)0===n?a="down":1===n&&(a="up"),n++,1<n&&(n=0);else if(6===player_data.drop_mode)0===n?a="left":1===n&&(a="right"),n++,1<n&&(n=0);else if(7===player_data.drop_mode)0===n?a="up":1===n&&(a="right"),n++,1<n&&(n=0);else if(8===player_data.drop_mode)0===
n?a="down":1===n&&(a="left"),n++,1<n&&(n=0);else if(9===player_data.drop_mode)0===n?a="up":1===n?a="right":2===n?a="down":3===n&&(a="left"),n++,3<n&&(n=0);else if(9<player_data.drop_mode){var b=Math.floor(4*Math.random());0===b?a="up":1===b?a="right":2===b?a="down":3===b&&(a="left")}b=a;a=0;if("down"===b)for(b=0;8>b;b++)for(var c=0,d=9;0<=d;d--)l[d][b].filled?(0!=c&&a++,l[d][b].to={x:0,y:c}):c++;else if("up"===b)for(b=0;8>b;b++)for(d=c=0;10>d;d++)l[d][b].filled?(0!=c&&a++,l[d][b].to={x:0,y:c}):c--;
else if("left"===b)for(b=0;10>b;b++)for(d=c=0;8>d;d++)l[b][d].filled?(0!=c&&a++,l[b][d].to={x:c,y:0}):c--;else if("right"===b)for(b=0;10>b;b++)for(c=0,d=7;0<=d;d--)l[b][d].filled?(0!=c&&a++,l[b][d].to={x:c,y:0}):c++;if(a){b=u.getLength();c=u.getChildren();for(var f=d=0;10>f;f++)for(var g=0;8>g;g++)if(l[f][g].filled){d++;var h=0;a:for(;h<b;h++){var m=c[h];if(m.pos.x===g&&m.pos.y===f){m.depth=d;break a}}}G(a)}else if(y="play",!x()){a:{for(a=0;10>a;a++)for(b=0;8>b;b++)if(l[a][b].filled){a=!1;break a}a=
!0}a?(PokiSDK.happyTime(.8),PokiSDK.gameplayStop(),play_sound("completed",p),y="bonus",a="hint",1===Math.floor(2*Math.random())&&(a="shuffle"),"hint"===a?player_data.hint_left++:"shuffle"===a&&player_data.shuffle_left++,p.add.rectangle(0,0,config.width,config.height,0).setOrigin(0).alpha=.8,p.add.text(360,320,"COMPLETED",{fontFamily:"PoetsenOne",fontSize:65,align:"center",color:"#FFFFFF"}).setOrigin(.5),p.add.sprite(360,480,a+"_icon"),p.add.text(360,600,"+1",{fontFamily:"PoetsenOne",fontSize:75,align:"center",
color:"#FFFFFF"}).setOrigin(.5),draw_button(360,700,"next",p),last_array=null,player_data.drop_mode++,l=null,W()):0<player_data.shuffle_left?(C.setVisible(!0),play_sound("nomatch",p)):(y="gameover1",setTimeout(S,1E3))}W()},100);T()},300)):(q.clearTint(),q=f,D.setPosition(f.x,f.y)):(q.clearTint(),q=f,D.setPosition(f.x,f.y))):"play"===y&&(play_sound("itemclick",p),q=f,f.setTint(5233606),D.setVisible(!0),D.setPosition(f.x,f.y))}},this);x()||last_array||this.scene.start("game")};
function play_sound(a,h){game_data.sound&&!ad_show&&h.sound.play(a)}function switch_audio(a){game_data[a.name]?(game_data[a.name]=!1,a.setTexture("btn_sound_off")):(game_data[a.name]=!0,a.setTexture("btn_sound_on"))}function check_audio(a){game_data[a.name]?a.setTexture("btn_sound_on"):a.setTexture("btn_sound_off")}function draw_button(a,h,g,v){a=v.add.sprite(a,h,"btn_"+g).setInteractive();a.button=!0;a.name=g;return a}
var config={type:Phaser.AUTO,width:720,height:1080,scale:{mode:Phaser.Scale.FIT,parent:"game_content",autoCenter:Phaser.Scale.CENTER_BOTH},scene:[Boot,Load,Menu,Game]},game;PokiSDK.init().then(function(){console.log("Poki SDK successfully initialized");game=new Phaser.Game(config)}).catch(function(){console.log("Initialized, but the user likely has adblock");game=new Phaser.Game(config)});PokiSDK.setDebug(!1);
