var CANVAS_WIDTH = 840;
var CANVAS_HEIGHT = 1360;

var EDGEBOARD_X = 72;
var EDGEBOARD_Y = 170;

var FPS = 30;
var FPS_TIME      = 1000/FPS;
var DISABLE_SOUND_MOBILE = false;

var PRIMARY_FONT = "CoopBlack";

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_CHOOSE_MODE = 2;
var STATE_HELP    = 3;
var STATE_GAME    = 4;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;
var ON_RELEASE_YES = 6;
var ON_RELEASE_NO  = 7;
var ON_COIN_ARRIVED = 8;

var NUM_SWIPE;
var ROTATION_OFFSET = 130/530*CANVAS_WIDTH;
var MAX_SPEED = 50;
var STARTING_MONEY_FACTOR_INCREASE = 0.06;
var STEP_MONEY_FACTOR = 0.014;
var MAX_MULTIPLIER = 5;
var TIME_BAR_MONEY_TWEEN = 50;
var TIME_MONEY_TWEEN = 50;
var SLOW_COEFF = 0.05;
var SPINNER_WIDTH = 500;
var SPINNER_HEIGHT = 500;
var SPINNER_CENTER_WIDTH = 144;
var SPINNER_CENTER_HEIGHT = 144;
var NUM_SPINNER = 12;
var NUM_ROWS_PAGE_LEVEL = 3;
var NUM_COLS_PAGE_LEVEL = 2;
var TWEEN_TYPE_0 = 0; //MONEY TWEEN USED FOR MULTIPLIER BAR
var TWEEN_TYPE_1 = 1; //MONEY TWEEN USED FOR SPINNER PURCHASE

var FRICTION_UPGRADE = new Array();
FRICTION_UPGRADE[0] = 0.96;
FRICTION_UPGRADE[1] = 0.97;
FRICTION_UPGRADE[2] = 0.975;
FRICTION_UPGRADE[3] = 0.98;
FRICTION_UPGRADE[4] = 0.99;
FRICTION_UPGRADE[5] = 0.992;
FRICTION_UPGRADE[6] = 0.994;

var PRICE_FRICTION = new Array();
PRICE_FRICTION[0] = 0;
PRICE_FRICTION[1] = 15;
PRICE_FRICTION[2] = 50;
PRICE_FRICTION[3] = 150;
PRICE_FRICTION[4] = 500;
PRICE_FRICTION[5] = 2000;
PRICE_FRICTION[6] = 5000;

var MAX_SPEED_UPGRADE = new Array();
MAX_SPEED_UPGRADE[0] = 50;
MAX_SPEED_UPGRADE[1] = 58;
MAX_SPEED_UPGRADE[2] = 65;
MAX_SPEED_UPGRADE[3] = 68;
MAX_SPEED_UPGRADE[4] = 74;
MAX_SPEED_UPGRADE[5] = 80;
MAX_SPEED_UPGRADE[6] = 85;

var PRICE_MAX_SPEED = new Array();
PRICE_MAX_SPEED[0] = 0;
PRICE_MAX_SPEED[1] = 10;
PRICE_MAX_SPEED[2] = 30;
PRICE_MAX_SPEED[3] = 100;
PRICE_MAX_SPEED[4] = 300;
PRICE_MAX_SPEED[5] = 1000;
PRICE_MAX_SPEED[6] = 3000;

var PRICE_SPINNER = new Array();
PRICE_SPINNER[0] = 0;
PRICE_SPINNER[1] = 100;
PRICE_SPINNER[2] = 200;
PRICE_SPINNER[3] = 300;
PRICE_SPINNER[4] = 500;
PRICE_SPINNER[5] = 1000;
PRICE_SPINNER[6] = 1500;
PRICE_SPINNER[7] = 2000;
PRICE_SPINNER[8] = 4000;
PRICE_SPINNER[9] = 5000;
PRICE_SPINNER[10] = 7500;
PRICE_SPINNER[11] = 10000;

var NUM_SPINS_FOR_ADS;
var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;