var TEXT_PLAYER_COLOUR = "SELECT P{0} COLOUR";

var TEXT_HELP1 = "THE GOOSE GAME IS A VERY OLD, WORLD-WIDE FAMOUS GAME.";
var TEXT_HELP2 = "THROW THE DICES AND REACH THE FINAL SQUARE BEFORE THE OTHER PLAYERS.";
var TEXT_HELP3 = "USE BONUS SQUARES AND AVOID TRAPS TO WIN!";
var TEXT_HELP4 = "SPECIAL TIPS";
var TEXT_HELP5 = "DUE TO THE GOOSE SQUARES DISPOSITION, WHEN A PLAYER ROLLS A 9 AT THE FIRST TURN, HE AUTOMATICALLY WINS THE GAME.";
var TEXT_HELP6 = "WHEN PLAYING WITH TWO PLAYERS ONLY, IF ONE OF THE PLAYERS GOES TO THE WELL SQUARE AND THE OTHER GOES TO THE PRISON SQUARE, IT'S GAME OVER. NO ONE WILL RESCUE YOU, OF COURSE";

var TEXT_SQUARE_GOOSE = "GOOSE SQUARE: REPEAT THE SAME SCORE AGAIN";
var TEXT_SQUARE_BRIDGE = "BRIDGE SQUARE: REPEAT THE SAME SCORE AGAIN";
var TEXT_SQUARE_HOUSE = "HOUSE SQUARE: STAY HERE FOR THREE TURNS";
var TEXT_SQUARE_WELL = "WELL SQUARE: STAY HERE UNTIL ANOTHER PLAYER WILL RESCUE YOU";
var TEXT_SQUARE_PRISON = "PRISON SQUARE: STAY HERE UNTIL ANOTHER PLAYER WILL RESCUE YOU";
var TEXT_SQUARE_MAZE = "MAZE SQUARE: SORRY, GO BACK TO SQUARE 39";
var TEXT_SQUARE_SKULL = "SKULL SQUARE: SORRY, GO BACK TO SQUARE 1";
var TEXT_SQUARE_FINISH = "FINAL SQUARE: REACH THIS SQUARE TO WIN THE GAME!!!";

var TEXT_SELECT_OPPONENTS = "SELECT OPPONENTS";
var TEXT_SELECT_PLAYERS = "SELECT PLAYERS";
var TEXT_SELECT_COLOUR = "SELECT YOUR COLOUR";
var TEXT_GAMES_PLAYED = "GAMES PLAYED";
var TEXT_GAMES_WON = "GAMES WON";
var TEXT_WIN = "YOU WON";
var TEXT_LOSE = "YOU LOSE";
var TEXT_PAUSE = "PAUSE";
var TEXT_ARE_SURE = "ARE YOU SURE?";

var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_CREDITS_DEVELOPED = "Developed by";

var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT LOCAL STORAGE. IF YOU'RE USING SAFARI, IT MAY BE RELATED TO PRIVATE BROWSING. AS A RESULT, SOME INFO MAY NOT BE SAVED OR SOME FEATURES MAY NOT BE AVAILABLE.";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better?";