var CANVAS_WIDTH = 1360;
var CANVAS_HEIGHT = 640;

var CANVAS_WIDTH_HALF = CANVAS_WIDTH * 0.5;
var CANVAS_HEIGHT_HALF = CANVAS_HEIGHT * 0.5;

var EDGEBOARD_X = 275;
var EDGEBOARD_Y = 5;

var FPS = 30;
var FPS_TIME = 1000 / FPS;
var DISABLE_SOUND_MOBILE = false;

var PRIMARY_FONT = "bd_cartoon_shoutregular";
var PRIMARY_FONT_COLOR = "#ffffff";
var SECONDARY_FONT_COLOR = "#000000";

var STATE_LOADING = 0;
var STATE_MENU = 1;
var STATE_HELP = 1;
var STATE_GAME = 3;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP = 1;
var ON_BACK_MENU = 6;
var ON_CHECK = 7;
var ON_RESTART = 8;

var MAZE_TIME;
var LOGO_TIME;
var HOUSE_PENALITIES;
var PRISON_PENALITIES;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;
var SOUNDTRACK_VOLUME_IN_GAME  = 0.3;

var LAST_SQUARE = 63;

var HUMAN_VS_HUMAN = 0;
var HUMAN_VS_CPU = 1;