var TEXT_GAMEOVER   = "TIME OVER";
var TEXT_SCORE      = "SCORE";
var TEXT_BEST_SCORE = "BEST SCORE";
var TEXT_ARE_YOU_SURE = "ARE YOU SURE?";
var TEXT_DEVELOPED  = "DEVELOPED BY";
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT LOCAL STORAGE. IF YOU'RE USING SAFARI, IT MAY BE RELATED TO PRIVATE BROWSING. AS A RESULT, SOME INFO MAY NOT BE SAVED OR SOME FEATURES MAY NOT BE AVAILABLE.";
var TEXT_PRELOADER_CONTINUE = "START";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";