TEXT_ARE_SURE = "ARE YOU SURE?";
TEXT_PAUSE = "PAUSE";
TEXT_RESET = "ARE YOU SURE? ALL YOUR PREVIOUS SCORES WILL BE DELETED!";

TEXT_POWER = "POWER";
TEXT_CHARACTERS_NAMES = ["OPPONENT", "PLAYER"];
TEXT_WIN = "YOU WON";
TEXT_LOSE = "YOU LOST";
TEXT_SET = "SET";
TEXT_OUT = "OUT";
TEXT_FAULT = "FAULT";
TEXT_SCORE_MATCH = "SCORE MATCH";
TEXT_TOTAL_SCORE = "TOTAL SCORE";
TEXT_SELECT_LEVEL = "SELECT A LEVEL";
TEXT_MATCH = "MATCH";
TEXT_HELP_DESKTOP_0 = "CLICK THE MOUSE BUTTON TO STOP THE POWER BAR AND SERVE THE BALL";
TEXT_HELP_MOBILE_0 = "TOUCH SCREEN TO STOP POWER BAR AND SERVE THE BALL";
TEXT_HELP_DESKTOP_1 = "MOVE THE MOUSE TO SET DIRECTION AND HEIGHT OF THE BALL";
TEXT_HELP_MOBILE_1 = "SWIPE TO SET DIRECTION AND HEIGHT OF THE BALL";
TEXT_HELP_DESKTOP_2 = "HOLD DOWN THE MOUSE BUTTON TO INCREASE THE SHOT'S POWER";
TEXT_HELP_MOBILE_2 = "HOLD DOWN TO INCREASE THE SHOT'S POWER";
TEXT_KMH = "KMH";
TEXT_WRONG = "NUMBER OF SET NOT VALID. PLEASE SET ONE OF THIS VALUES FOR SET NUMBER: 1, 3, 5";

TEXT_COLOR_0 = "#fff";
TEXT_COLOR_1 = "#000";
TEXT_COLOR_2 = "#e49f0c";
TEXT_COLOR_3 = "#ec9706";
TEXT_COLOR_4 = "#4f8ede";
TEXT_COLOR_5 = "#6a727c";

TEXT_SHADOWN_ALPHA = 0.6;
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better";