TEXT_SCORE      = "SCORE: ";

TEXT_POSITION   = "° PLACE";
TEXT_SCORE      = "SCORE:       ";

TEXT_CREDITS_DEVELOPED = "Developed by";

TEXT_START_MOVEMENT        = "MASH THE LEFT AND RIGHT KEYS TO BOOST YOUR POWER";
HELP_TEXT_BAR              = "PRESS THE SPACE BAR WHEN THE ARROW IS AT THE VERY CENTRE TO MAKE THE PERFECT TURN";
TEXT_START_MOVEMENT_MOBILE = "MASH THE LEFT AND RIGHT BUTTONS TO BOOST YOUR POWER";
HELP_TEXT_BAR_MOBILE       = "PRESS THE BUTTON WHEN THE ARROW IS AT THE VERY CENTRE TO MAKE THE PERFECT TURN";
HELP_ENERGY                = "KEEP YOUR ENERGY BAR FULL TO GO FASTER!";
TEXT_ON_EXIT               = "ARE YOU SURE?";
TEXT_ON_CAREER_RESET       = "ARE YOU SURE? ALL YOUR PREVIOUS SCORES WILL BE DELETED!";

TEXT_CURRENCY   = "$";
TEXT_LANE = "Lane";
TEXT_TIME = "Time";

TEXT_TEAM_0 = "U.S.A.";
TEXT_TEAM_1 = "CHINA";
TEXT_TEAM_2 = "U.K.";
TEXT_TEAM_3 = "FRANCE";
TEXT_TEAM_4 = "AUSTRALIA";
TEXT_TEAM_5 = "GERMANY";
TEXT_TEAM_6 = "ITALY";
TEXT_TEAM_7 = "BRAZIL";

TEXT_CREDITS    =   "CREDITS";
TEXT_SWIMMER    =   "SELECT SWIMMER";
TEXT_MODE       =   "SELECT MODE";
TEXT_CHALLENGE  =   "SELECT CHALLENGE";
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better";
