var CANVAS_WIDTH = 1360;
var CANVAS_HEIGHT = 640;

var EDGEBOARD_X = 275; 
var EDGEBOARD_Y = 50;

var FONT = "arialbold";
var FONT_2 = "pixel_lcd7regular";

var FPS = 30;
var FPS_TIME      = 1000/FPS;
var DISABLE_SOUND_MOBILE = false;

var PLAYER_X_POSITION_IN_SELECTION = CANVAS_WIDTH/2;
var PLAYER_Y_POSITION_IN_SELECTION = CANVAS_HEIGHT/2+29;

var NUM_SWIMMERS = 8;

var HALF_DIVE_ANIMATION_FRAME = 7;
var HALF_TURN_ANIMATION_FRAME = 8;

var PLAYER_DIVE_WIDTH             = 131;
var PLAYER_DIVE_HEIGHT            = 170;
var WATER_DIVE_WIDTH              = 113;
var WATER_DIVE_HEIGHT             = 135;
var PLAYER_SWIMMING_WIDTH         = 137;
var PLAYER_SWIMMING_HEIGHT        = 85;
var PLAYER_SWIMMING_FRONT_WIDTH   = 139;
var PLAYER_SWIMMING_FRONT_HEIGHT  = 83;
var PLAYER_TURN_WIDTH             = 145;
var PLAYER_TURN_HEIGHT            = 107;
var PLAYER_IDLE_WIDTH             = 82;
var PLAYER_IDLE_HEIGHT            = 120;

var SHOT_INDICATOR_SPEED;

var NUM_ROUNDS;
var NUM_POWER_UP_AVAILABLE = 4;

var RANGE_HEIGHT = 5;
var BARX = 44;
var BARY = 359;
var CURSOR_X = 41;
var CURSOR_Y = 41;

var PLAYER_MAX_SPEED;
var PLAYER_MIN_SPEED;
var PLAYER_ENERGY;
var PLAYER_RESISTENCE_STEP;
var PLAYER_MAX_SPEED_ADDER;
var PLAYER_ENERGY_ADDER;

var DIVE_ANIMATION              = 0;
var SWIMMING_ANIMATION          = 1;
var TURN_ANIMATION              = 2;
var SWIMMING_FRONT_ANIMATION    = 3;
var TURN_FRONT_ANIMATION        = 4;
var IDLE_ANIMATION              = 5;

var SPEED_ON_DIVE        = 8;
var DECELERATION_ON_TURN = 0.75;
var SPEED_DECELERATION   = 0.03;
var SPEED_MIN_ON_TURN    = 0.2;
var SPEED_MIN_FOR_IDLE   = 0.15;
var MODIFIER_SPEED_ADDER = 0.5;

var ENEMY_MAX_SPEED = [4, 4, 5, , 6, 5, 4, 4];
var ENEMY_MIN_SPEED = [1, 2, 3, , 3, 2, 2, 1];
var ENEMY_ENERGY = [100, 100, 100, , 100, 100, 100, 100];
var ENEMY_RESISTENCE_STEP = [1.3, 1.5, 1.5, , 1.5, 1.5, 1.5, 1.3];
var ENEMY_OCCURRENCE_SWIM = [0.2, 0.15, 0.2, , 0.25, 0.2, 0.15, 0.2];

var PLAYER_NAME_AND_SPRITE;

var WAIT_FOR_GAME_START = 0;
var CONFIRMATION_ON_EXIT = 1;
var CONFIRMATION_ON_CAREER_RESET = 2;

var TEAM_0 = 0;
var TEAM_1 = 1;
var TEAM_2 = 2;
var TEAM_3 = 3;
var TEAM_4 = 4;
var TEAM_5 = 5;
var TEAM_6 = 6;
var TEAM_7 = 7;

var LEFT_DIR      = 37;
var UP_DIR        = 38;
var RIGHT_DIR     = 39;
var DOWN_DIR      = 40;
var SPACEBAR      = 32;

var EASY        = 1;
var NORMAL      = 2;
var HARD        = 4;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;