var CANVAS_WIDTH = 1280;
var CANVAS_HEIGHT = 768;

var EDGEBOARD_X = 90;
var EDGEBOARD_Y = 105;

var PRIMARY_FONT = "ArialBold";

var FPS           = 60;
var FPH           = FPS*3600;
var FPS_TIME      = 1000/FPS;
var CAR_REAL_LENGTH = 4.5;
var CAR_PIXEL_LENGTH = 370;
var PIXEL_TO_METER_RATIO = CAR_REAL_LENGTH/CAR_PIXEL_LENGTH;
var METER_TO_PIXEL_RATIO = CAR_PIXEL_LENGTH/CAR_REAL_LENGTH;
var PARALLAX_BG_RATIO = 1/20;
var PARALLAX_1_RATIO = 1/5;
var PARALLAX_2_RATIO = 1.2;
var LAMP_WIDTH;
var LAMP_OFFSET = 570;

var DISABLE_SOUND_MOBILE = false;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_MODEMENU    = 2;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;

var STATE_HELP_PANEL = -1;
var STATE_START_BATTLE = 0;
var STATE_RACE_RUN = 1;
var STATE_RACE_FINISH = 2;

var GEAR_N = 0;

var NULL_AREA = -1;
var GREEN_AREA = 0;
var EARLY_AREA = 1;
var LATE_AREA = 2;

var STATE_HUD_NULL = -1;
var STATE_HUD_STALL = 0;
var STATE_HUD_UPDATE = 1;
var STATE_HUD_REPOSITIONING = 2;

var STATE_ENGINE_STALL = 0;
var STATE_ENGINE_UPDATE = 1;
var STATE_ENGINE_BREAK = 2;

var ENGINE_NORMAL_RPM_ACCELERATION = 1;
var ENGINE_NITRO_RPM_ACCELERATION = 3;
var NITRO_INFO;
var NITRO_DURATION = 0;

var BREAK_DURATION = 4000;

var START_COUNTDOWN = 3000;

var HUD_DOWNSHIFT_GEAR_DURATION = 500;
var HUD_RPM_INTERVAL = [{min: -90, max: 80}, {min: -90, max: 70}, {min: -50, max: 65}, {min: -40, max: 60}, {min: -40, max: 65}, {min: -30, max: 75}, {min: -10, max: 85}];

var WRONG_GEAR_DURATION_INFO;
var WRONG_GEAR_CHANGE_STALL_DURATION = 0;
var GEAR_START_GREEN_WIDTH;
var GEAR_INRACE_GREEN_WIDTH;
var START_ACCELERATION_INDICATOR_SPEED = 2;
var GEAR_START_AREA = {center: 45, greenangle: 0, earlyangle:0, lateangle:0};
var GEAR_IN_RACE_AREA = {greenangle: 0, earlyangle:20, lateangle:20};
var GEAR_NULL_AREA = {greenangle: 0, earlyangle:0, lateangle:0};

var NUM_TRACK = 10;
var START_LINE_X = 600;
var STAGE_METER_LENGTH = new Array();

var STAGE_WIN_REWARDS;

var BONUS_REWARD_TRACKLENGTH_MULTIPLIER;
var BONUS_REWARD_OVERTAKING_MULTIPLIER;
var BONUS_REWARD_DIFFICULTY_MULTIPLIER;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;