TEXT_SCORE      = "SCORE: ";
TEXT_PAUSE      = "PAUSE";
TEXT_BONUS      = "BONUS";
TEXT_CONGRATS   = "CONGRATULATIONS!!";
TEXT_GOAL_SCORED = "GOAL SCORED";
TEXT_TEAM_0      = "ARGENTINA";
TEXT_TEAM_1      = "BRAZIL";
TEXT_TEAM_2      = "GERMANY";
TEXT_TEAM_3      = "ENGLAND";
TEXT_TEAM_4      = "ITALY";
TEXT_TEAM_5      = "FRANCE";
HELP_TEXT_DESKTOP = "PRESS SPACEBAR TO CHOSE POINT WHERE KICKING BALL ON HORIZONTAL AND VERTICAL AXIS!!";
var TEXT_PRELOADER_CONTINUE = "START";


HELP_TEXT_MOBILE  = "TAP ON THE SCREEN TO CHOSE POINT WHERE KICKING BALL ON HORIZONTAL AND VERTICAL AXIS!!";

HELP_TEXT          = "TRY TO BE QUICK! THE BONUS MULTIPLIER DECREASES RAPIDLY EACH SECOND. EVERY GOAL "+
                     "INCREASES YOUR SCORE, MULTIPLYING IT BY THE MULTIPLIER!";
TEXT_DEVELOPED = "DEVELOPED BY";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better";
