var CANVAS_WIDTH = 1360;
var CANVAS_HEIGHT = 640;

var EDGEBOARD_X = 275; 
var EDGEBOARD_Y = 80;

var FONT_GAME = "walibi0615bold";
var FPS_TIME      = 1000/24;
var DISABLE_SOUND_MOBILE = false;

var NUM_CROWD = 31;
var NUM_LEVEL = 6;
var NUM_KICK  = 5;

var SPACE_BAR = 32;
var LEFT      = 37;
var RIGHT     = 39;
var UP        = 38;
var DOWN      = 40;

var SHOT_INDICATOR_SPEED;
var DECREASE_SHOT_INDICATOR_SPEED;
var RANGE_WIDTH  = 9;
var RANGE_HEIGHT = 4;

var LOW_PERCENT   = 5;
var MED_PERCENT   = 50;
var HIGH_PERCENT  = 90;

var MATRIX_X_START = 380;
var MATRIX_X_END   = 1040;
var MATRIX_Y_START = 235;
var MATRIX_Y_END   = 430;

var ROUND = 0;

var MSG_BOX_WIDTH  = 744;
var MSG_BOX_HEIGHT = 450;
var GOAL_WIDTH     = 390;
var GOAL_HEIGHT    = 145;

var PLAYER_WIDTH   = 160;
var PLAYER_HEIGHT  = 239;

var WALL_WIDTH      = 119;
var WALL_HEIGHT     = 179;

var BALL_WIDTH  = 60;
var BALL_HEIGHT = 60;
var STEP_SPEED_BALL_HITTED = 2.4;

var TOP_BARX = 784;
var TOP_BARY = 48;
var RIGHT_BARX = 44;
var RIGHT_BARY = 359;
var CURSOR_X = 41;
var CURSOR_Y = 41;

var PLAYER_X_POSITION_IN_SELECTION = CANVAS_WIDTH/2;
var PLAYER_Y_POSITION_IN_SELECTION = 350;

var ARGENTINA = 0;
var BRAZIL    = 1;
var GERMANY   = 2;
var ENGLAND   = 3;
var ITALY     = 4;
var FRANCE    = 5;

var FIRST_TIME = 0;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;