function m(b,a,c,d){b.l.pb(b.tb,a,c,d)}function n(b,a,c,d){b.l.ba?m(b,a,c,d):b.l.cf()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.l.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)p(b,c,d)}function w(b){b.Zb||(b.l.Fc(b.le),b.Zb=!0)}window.Da=class{constructor(b,a){this.l=b;this.tb=a;this.Zb=!1;this.le=()=>this.Sa()}sc(){}Sa(){}};
window.Qf=class{constructor(){this.pd=-1}j(){-1!==this.pd&&(self.clearTimeout(this.pd),this.pd=-1)}};"use strict";function ba(b,a){p(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}function x(b,a){b=b.Xa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Wb}
window.wd=class extends self.Da{constructor(b,a){super(b,a);this.Xa=new Map;this.rb=!0;v(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=x(this,c);this.rb&&d.parentElement.removeChild(d);this.Xa.delete(c)}],["set-visible",c=>{if(this.rb){var d=this.Xa.get(c.elementId),e=d.Wb;d.Vd?e.style.display=c.isVisible?"":"none":d.xf=!!c.isVisible}}],["update-position",c=>{if(this.rb){var d=this.Xa.get(c.elementId),e=d.Wb,f=this.l;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.Cf=g;g=f.yd(g);g!==d.Ja&&(e.remove(),f.xc(g).appendChild(e),d.Ja=g,f.Qc());c=c.htmlZIndex;c!==d.Zc&&(d.Zc=c,f.Qc());d.Vd||(d.Vd=!0,d.xf&&(e.style.display=""))}}],["update-state",c=>{x(this,c.elementId);throw Error("required override");}],["focus",c=>this.Nc(c)],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,
c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}Nc(b){var a=x(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ea=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Gf?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.Kf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function fa(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let A=new Audio;
const ha={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ia(b){b=await ja(b);return(new TextDecoder("utf-8")).decode(b)}
function ja(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let D=0;window.RealFile=window.File;const E=[],G=new Map,H=new Map;let ka=0;const la=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");la.push(b)};const pa=new Set(["cordova","playable-ad","instant-games"]);let ra=!1;
window.qa=class b{constructor(a){this.ba=a.Mf;this.za=null;this.aa="";this.fb=a.Jf;this.Jb={};this.Za=this.wa=null;this.Wa=[];this.na=null;this.Zd=!0;this.M=[];this.jd=[];this.kd=!1;this.me=()=>this.af();this.ad=!1;this.Sd=0;this.yb=null;this.eb=-1;this.Bf=()=>this.mf();this.Gb=new Set;this.qd=null;this.ne=[];this.u=a.pe;this.$b="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.ba=!1;da&&(this.ba=!1);if("cordova"===this.u&&this.ba&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.pa()?self.chrome.webview.addEventListener("message",c=>this.Id(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Id(c));this.cc=this.ta=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.rf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.gf());this.B("runtime","cordova-fetch-local-file",c=>this.hf(c));this.B("runtime","create-job-worker",()=>this.jf());this.B("runtime","send-wrapper-extension-message",c=>this.qf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Pb(a)):this.Pb(a)}j(){this.Gc();this.za&&(this.za=this.za.onmessage=null);this.wa&&(this.wa.terminate(),this.wa=null);this.Za&&(this.Za.j(),this.Za=null);for(const {canvas:a,
ib:c}of this.M)a.remove(),c.remove();this.M.length=0}Ie(){return this.M[0].canvas}yd(a){return Math.min(a,this.M.length-1)}xc(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].ib}Oe(){return ca&&"cordova"===this.u}nb(){const a=navigator.userAgent;return ca&&pa.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Me(){return y}zd(){return y&&pa.has(this.u)}Bd(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}pa(){return this.Bd()||"xbox-uwp-webview2"===this.u}async Pb(a){this.ba&&!await fa()&&(this.ba=!1);"macos-wkwebview"===this.u?this.Ha({type:"ready"}):this.pa()&&(this.tf(),this.ne=(await this.ff()).registeredComponentIds);if("playable-ad"===this.u){this.ta=self.c3_base64files;this.cc={};await this.Ye();for(let d=0,e=a.hb.length;d<e;++d){var c=a.hb[d];this.cc.hasOwnProperty(c)?a.hb[d]={Gf:!0,Kf:this.cc[c]}:this.ta.hasOwnProperty(c)&&(a.hb[d]=URL.createObjectURL(this.ta[c]))}a.rc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Fc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.If?this.aa=a.If:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Of&&(this.Jb=a.Of);c=new MessageChannel;this.za=c.port1;this.za.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.lf(d));this.yb=
new self.Pe(this);await sa(this.yb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.ef(a,c.port2):await this.df(a,c.port2)}Ic(a){a=this.Jb.hasOwnProperty(a)?this.Jb[a]:a.endsWith("/workermain.js")&&this.Jb.hasOwnProperty("workermain.js")?this.Jb["workermain.js"]:"playable-ad"===
this.u&&this.ta.hasOwnProperty(a)?this.ta[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async uc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.$b)return a=await this.Lb(d.Ff?a:this.fb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}ra(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}wc(){return this.pa()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.u)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Gd(a){var c=this.aa,d=location.href,e=this.ra(),f=this.ha(),g=this.wc(),
h=window.devicePixelRatio,k=b.mb(),l=a.Wf,q=window.cr_previewImageBlobs||this.ta,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.pe;var aa=(new URLSearchParams(self.location.search)).has("debug"),F=this.yb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:q,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,exportType:a,isDebug:aa,
ife:!!self.Uf,jobScheduler:{inputPort:F.$c,outputPort:F.hd,maxNumWorkers:F.yf},supportedAudioFormats:ha,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fb+"opus.wasm.wasm",isFileProtocol:this.$b,isiOSCordova:this.Oe(),isiOSWebView:this.nb(),isWindowsWebView2:this.Bd(),isAnyWebView2Wrapper:this.pa(),wrapperComponentIds:this.ne,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ef(a,c){const d=this.Ic(a.Nf);"preview"===
this.u?(this.wa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,q)=>{const r=t=>{this.wa.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():q()};this.wa.addEventListener("message",r);this.wa.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.wa=await this.uc(d,this.aa,{type:"module",name:"Runtime",Ff:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);
const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,ib:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.rc||[],k=a.hb;h=await Promise.all(h.map(l=>this.Ta(l)));k=await Promise.all(k.map(l=>this.Ta(l)));if("cordova"===this.u)for(let l=0,q=a.qc.length;l<q;++l){const r=a.qc[l],t=r[0];if(t===a.rd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ta(t)}this.wa.postMessage(Object.assign(this.Gd(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.qc,mainProjectScript:a.rd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...ta(this.yb)]);this.Wa=E.map(l=>new l(this));this.Fd();ua(e);va(g);wa(this.na);self.c3_callFunction=(l,q)=>{var r=this.na;return r.l.Cd(r.tb,"js-invoke-function",{name:l,params:q})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.pb("runtime","go-to-last-error-script"))}async df(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,ib:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Wa=E.map(h=>new h(this));this.Fd();ua(d);va(e);e=a.hb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.rc)){var f=[...a.rc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Ta(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.rd;const g=a.qc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ta(k),await z(k),"preview"!==this.u||e[h]||this.Kd(h,"main script did not run to completion")}catch(l){this.Kd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Ta(k),await z(k);"preview"===this.u&&"object"!==typeof self.Pf.Rf?(this.Rb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Gd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:la}),wa(this.na),this.Hd(),this.Za=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Za,a))}Kd(a,c){this.Rb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Hd(){this.Rb()}Rb(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async jf(){const a=await xa(this.yb);return{outputPort:a,transferables:[a]}}rf(a){if(!this.ad){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,ib:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Zd&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Zd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,ib:q}=this.M.pop();q.remove();this.ba&&!d?this.jd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,q=c-this.M.length;l<q;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,ua(c),va(d),this.M.push({canvas:c,ib:d});for(const l of this.Wa)if(l instanceof window.wd&&l.rb)for(const q of l.Xa.values())e=l.l.yd(q.Cf),f=q.Ja,-1!==
e&&-1!==f&&e!==f&&(f=q.Wb,f.remove(),l.l.xc(e).appendChild(f),q.Ja=e);this.Qc();return{addedCanvases:a,transferables:k}}gf(){for(const a of this.jd)a.remove();this.jd.length=0}Qc(){this.kd||(this.kd=!0,this.Fc(this.me))}af(){this.Jd(this.me);this.kd=!1;let a=[];for(var c of this.Wa)if(c instanceof window.wd){var d=c.rb?[...c.Xa.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ja,l=h.Ja;return k!==l?k-l:g.Zc-h.Zc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ja!==c&&(this.Ed(c,a.slice(d,
e)),c=g.Ja,d=e)}d<e&&this.Ed(c,a.slice(d,e))}Ed(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Wb);var d=new Set(c);a=this.xc(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}cf(){if(this.ba)throw Error("not available in worker mode");return this.Za}pb(a,c,d,e,f){this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}Cd(a,c,d,e,f){const g=ka++,h=new Promise((k,l)=>{H.set(g,{resolve:k,reject:l})});this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.kf(a);if("result"===c)this.nf(a);else if("runtime-ready"===c)this.pf();else if("alert-error"===c)this.Rb(),alert(a.message);else if("creating-runtime"===c)this.Hd();else throw Error(`unknown message '${c}'`);}kf(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Qb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Qb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Qb(f,!1,""+h)}):this.Qb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Qb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.za.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}nf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Pa(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Fd(){for(const a of this.Wa)if("runtime"===a.tb){this.na=a;return}throw Error("cannot find runtime DOM handler");
}lf(a){this.pb("debugger","message",a)}pf(){for(const a of this.Wa)a.sc()}static mb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ra)}static Sb(a){ra=!!a}Fc(a){this.Gb.add(a);this.Pc()}Jd(a){this.Gb.delete(a);0===this.Gb.size&&this.Gc()}Pc(){-1===this.eb&&0<this.Gb.size&&(this.eb=requestAnimationFrame(this.Bf))}Gc(){-1!==this.eb&&(cancelAnimationFrame(this.eb),this.eb=-1)}mf(){this.eb=-1;for(const a of this.Gb)a();this.Pc()}Ga(a){this.na.Ga(a)}Ra(a){this.na.Ra(a)}Oc(){this.na.Oc()}Ob(a){this.na.Ob(a)}Ne(){return!!ha["audio/webm; codecs=opus"]}async uf(a){a=
await this.Cd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ue(a){this.ad=!0;this.Sd=a}Le(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Ad(a){return!this.Le(a)}async Ta(a){return"cordova"===this.u&&(a.startsWith("file:")||this.$b&&this.Ad(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Lb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async hf(a){const c=a.filename;switch(a.as){case "text":return await this.Ge(c);
case "buffer":return await this.Lb(c);default:throw Error("unsupported type");}}vd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ge(a){a=await this.vd(a);return await ia(a)}Hc(){if(C.length&&!(8<=D)){D++;var a=C.shift();this.Ze(a.filename,a.Lf,a.Ef)}}Lb(a){return new Promise((c,d)=>{C.push({filename:a,Lf:e=>{D--;this.Hc();c(e)},Ef:e=>{D--;this.Hc();d(e)}});this.Hc()})}async Ze(a,c,d){try{const e=
await this.vd(a),f=await ja(e);c(f)}catch(e){d(e)}}Id(a){if("entered-fullscreen"===a)b.Sb(!0),I(this.na);else if("exited-fullscreen"===a)b.Sb(!1),I(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.qd(a),this.qd=null):"extension-message"===c?this.pb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}qf(a){this.Ha({type:"extension-message",componentId:a.componentId,messageId:a.messageId,
params:a.params||[],asyncId:a.asyncId})}Ha(a){this.pa()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}tf(){window.moveTo=(a,c)=>{this.Ha({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ha({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}ff(){return this.pa()?new Promise(a=>{this.qd=a;this.Ha({type:"wrapper-init"})}):
Promise.resolve()}async Ye(){const a=[];for(const [c,d]of Object.entries(this.ta))a.push(this.Xe(c,d));await Promise.all(a)}async Xe(a,c){if("object"===typeof c)this.ta[a]=new Blob([c.str],{type:c.type}),this.cc[a]=c.str;else{let d=await this.bf(c);d||(d=this.$e(c));this.ta[a]=d}}async bf(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}$e(a){a=this.sf(a);return this.We(a.data,a.Hf)}sf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Hf:a,data:d}}We(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const J=self.qa,ya=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},za={dispatchUserScriptEvent:!0},Aa={dispatchRuntimeEvent:!0};function Ba(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Ca(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Ea(b){b=URL.createObjectURL(b);try{return await Ca(b)}finally{URL.revokeObjectURL(b)}}function Fa(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ga=new Set(["input","textarea","datalist","select"]),Ha=new Set(["canvas","body","html"]);
function L(b){b.target.tagName&&Ha.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ia(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ja(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Ea(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ea(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ka=!1;document.addEventListener("pause",()=>Ka=!0);document.addEventListener("resume",()=>Ka=!1);function ua(b){b.addEventListener("selectstart",L);b.addEventListener("gesturehold",L);b.addEventListener("pointerdown",L)}function va(b){b.addEventListener("selectstart",Ia);b.addEventListener("gesturehold",Ia);b.addEventListener("touchstart",Ia)}function wa(b){b.Rd=!0;b.dd=b.l.ra();b.zb=b.l.ha()}
function I(b){if(!b.la){var a=J.mb();a&&"any"!==b.nd&&La(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ra(),innerHeight:b.ha()})}}async function Ma(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Na(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Oa(b){return await self.C3_GetSvgImageSize(b.blob)}function Pa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Qa(b){self.setTimeout(()=>{b.Qd=!0},1E3);"cordova"===b.l.u?(document.addEventListener("pause",()=>Ra(b,!0)),document.addEventListener("resume",()=>Ra(b,!1))):document.addEventListener("visibilitychange",()=>Ra(b,"hidden"===document.visibilityState));b.hc=!("hidden"!==document.visibilityState&&!Ka);return{isSuspended:b.hc}}
function Sa(b){b.Md||(b.Md=!0,window.addEventListener("deviceorientation",a=>{b.la||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.la||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ta(b){b.Ld||(b.Ld=!0,window.addEventListener("devicemotion",a=>{if(!b.la){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Ua(b){await Ba(b.url)}
function Va(b,a){b.Td=a.message;-1===b.Uc&&(b.Uc=setTimeout(()=>{b.Uc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Td)},250))}function Wa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.mb(),innerWidth:b.ra(),innerHeight:b.ha()})}
function Ra(b,a){b.hc!==a&&((b.hc=a)?b.l.Gc():b.l.Pc(),m(b,"visibilitychange",{hidden:a}),!a&&b.l.nb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Xa(b,a,c){"Backspace"===c.key&&L(c);"nwjs"===b.l.u&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.la){var d=ya.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K)}}
function M(b,a,c,d){b.la||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Ca,pageX:c.pageX,pageY:c.pageY+b.Ca,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.la){var d=0;"mouse"===c.pointerType&&(d=b.fd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Ca,pageX:c.pageX,pageY:c.pageY+b.Ca,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.fd=c.buttons)}}function Ya(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Ca=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Ca=a))}}
function Za(b,a,c,d){const e=b.ra(),f=b.ha();b.gb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb(),cssDisplayMode:b.l.wc()}):10>d&&$a(b,e,f,d+1)}function $a(b,a,c,d){-1!==b.gb&&clearTimeout(b.gb);b.gb=setTimeout(()=>Za(b,a,c,d),48)}
function La(b){b=b.nd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function ab(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Pa(class extends self.Da{constructor(b){super(b,"runtime");this.Rd=!1;this.gb=-1;this.nd="any";this.hc=this.Ld=this.Md=!1;this.nc=document.createElement("div");this.nc.className="c3-screen-reader-text";this.nc.setAttribute("aria-live","polite");document.body.appendChild(this.nc);this.La=null;this.la=!1;this.Td="";this.Uc=-1;this.Qd=!1;this.dd=b.ra();this.zb=b.ha();this.Ca=this.Ib=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ma(c));b.B("runtime","raster-svg-image",c=>Na(c));b.B("runtime","get-svg-image-size",c=>Oa(c));b.B("runtime","set-target-orientation",c=>{this.nd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Pa(c));b.B("runtime","go-to-script",c=>Pa(c));b.B("runtime","before-start-ticking",()=>Qa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.La||(this.La=document.createElement("div"),this.La.id="inspectOutline",document.body.appendChild(this.La));var d=this.La;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.La&&(this.La.style.display="none")});b.B("runtime","enable-device-orientation",()=>Sa(this));b.B("runtime","enable-device-motion",()=>Ta(this));b.B("runtime","add-stylesheet",c=>Ua(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Lc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.nc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.la=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.l.Ie().style.display="";this.l.Ue(c.duration)});b.B("runtime","export-to-video-progress",c=>Va(this,c));b.B("runtime","exported-to-video",c=>{window.Df({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.Df({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Fa(d)||c.preventDefault()});window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});window.addEventListener("pointerdown",L,{passive:!1});this.fd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ja,{passive:!1});window.addEventListener("wheel",Ja,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.la&&this.Rd){var c=this.ra();var d=this.ha();if(this.l.zd()){if(this.Qd){if(this.dd===
c&&d<this.zb){this.Ib=this.zb-d;Ya(this,this.zb,this.Ib);c=void 0;break a}0<this.Ib&&(this.Ib=0,Ya(this,d,this.Ib))}this.dd=c;this.zb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb(),cssDisplayMode:this.l.wc()});this.l.nb()&&(-1!==this.gb&&clearTimeout(this.gb),Za(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",
()=>I(this));window.addEventListener("fullscreenerror",c=>Wa(this,c));window.addEventListener("webkitfullscreenerror",c=>Wa(this,c));window.addEventListener("mozfullscreenerror",c=>Wa(this,c));if(b.nb()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.$a=new Set;this.ec=new WeakSet;this.ya=!1}sc(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Aa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},Aa);this.fd=0});window.addEventListener("focusin",a=>{a=a.target;(Ga.has(a.tagName.toLowerCase())||Fa(a))&&m(this,"keyboard-blur",null,Aa)});window.addEventListener("keydown",a=>Xa(this,"keydown",a));window.addEventListener("keyup",a=>Xa(this,"keyup",a));window.addEventListener("mousedown",a=>M(this,"mousedown",a,
za));window.addEventListener("mousemove",a=>M(this,"mousemove",a,za));window.addEventListener("mouseup",a=>M(this,"mouseup",a,za));window.addEventListener("dblclick",a=>M(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.la||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Ca,pageX:a.pageX,pageY:a.pageY+this.Ca,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
ab(a.target)&&document.activeElement&&!ab(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.l.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Oc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.l.Me()&&!this.l.zd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Ya(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}));this.l.nb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}ra(){return this.l.ra()}ha(){return this.l.ha()}Oc(){var b=
[...this.$a];this.$a.clear();if(!this.ya)for(const a of b)(b=a.play())&&b.catch(()=>{this.ec.has(a)||this.$a.add(a)})}Ga(b){if("function"!==typeof b.play)throw Error("missing play function");this.ec.delete(b);let a;try{a=b.play()}catch(c){this.$a.add(b);return}a&&a.catch(()=>{this.ec.has(b)||this.$a.add(b)})}Ra(b){this.$a.delete(b);this.ec.add(b)}Ob(b){this.ya=!!b}Lc(b){alert(b.message)}});"use strict";
async function sa(b){if(b.vf)throw Error("already initialised");b.vf=!0;var a=b.Aa.Ic(("playable-ad"===b.Aa.u?b.Aa.fb:"")+"dispatchworker.js");b.Tc=await b.Aa.uc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.$c=a.port1;b.Tc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.hd=await xa(b)}function ta(b){return[b.$c,b.hd]}
async function xa(b){const a=b.$d.length;var c=b.Aa.Ic(("playable-ad"===b.Aa.u?b.Aa.fb:"")+"jobworker.js");c=await b.Aa.uc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Tc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.$d.push(c);return e.port1}
self.Pe=class{constructor(b){this.Aa=b;this.sb=b.aa;this.sb="preview"===b.u?this.sb+"workers/":this.sb+b.fb;this.yf=Math.min(navigator.hardwareConcurrency||2,16);this.Tc=null;this.$d=[];this.hd=this.$c=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.qa({Mf:!1,Nf:"workermain.js",hb:["scripts/c3runtime.js"],qc:[],rd:"",Jf:"scripts/",rc:[],pe:"html5"}));"use strict";
async function bb(b,a){a=a.type;let c=!0;0===a?c=await cb():1===a&&(c=await db());m(b,"permission-result",{type:a,result:c})}async function cb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function db(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.qa.Pa(class extends self.Da{constructor(b){super(b,"touch");p(this,"request-permission",a=>bb(this,a))}});"use strict";const eb=180/Math.PI;
async function fb(b,a){if(a.isiOSCordova||a.isSafari)b.jc=!0;b.od=a.timeScaleMode;b.ee=["equalpower","HRTF","soundfield"][a.panningModel];b.Pd=["linear","inverse","exponential"][a.distanceModel];b.fe=a.refDistance;b.de=a.maxDistance;b.he=a.rolloffFactor;if(b.l.ad)b.jc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.l.Sd)});else{var c={latencyHint:a.latencyHint};b.ke||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");gb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&gb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Va=b.g.createGain();b.Va.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>O(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function hb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,q=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.ae=g.slice(0);ib(b,g);try{b.R=await kb(b,c,d,e,g,f);if(q){P(b.R,!0);var u=b.R,aa=q.x,F=q.y,Ab=q.z,Bb=q.angle,ma=q.innerAngle,na=q.outerAngle,oa=q.outerGain;if(u.xb){lb(u,aa,F,Ab,Bb);var B=self.jb.Ve;
u.ua[0]!==B(ma)&&(u.ua[0]=B(ma),u.F.coneInnerAngle=B(ma));u.ua[1]!==B(na)&&(u.ua[1]=B(na),u.F.coneOuterAngle=B(na));u.ua[2]!==oa&&(u.ua[2]=oa,u.F.coneOuterGain=oa)}q.hasOwnProperty("uid")&&(b.R.sa=q.uid)}else"number"===typeof r&&0!==r?(Q(b.R,!0),mb(b.R,r)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,l,t)}catch(Cb){console.error("[Construct] Audio: error starting playback: ",Cb);return}finally{c=g.join(" ");d=b.Fb.get(c);if(!d)throw Error("expected pending tag");d.sd--;0===d.sd&&(d.resolve(),b.Fb.delete(c))}w(b)}
async function nb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await ob(b,c);for(const h of R(b,c))if(!h.xa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Oa=d;h.Ya=g;h.je=a}S(b)}async function pb(b,a){const c=a.tags;a=a.rate;await ob(b,c);for(const d of R(b,c))d.ma!==a&&(d.ma=a,d.Ia())}async function qb(b,a){const c=a.tags;a=a.pos;await ob(b,c);for(const d of R(b,c))d.Cc(a)}
async function rb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await kb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function sb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function tb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ve(b,...e);else if("delay"===c)d=new self.te(b,...e);else if("convolution"===c){var g=d=new self.se(b,f.ia,...e),h=a.bufferType;g.Nd=a.bufferOriginalUrl;g.Od=h}else if("flanger"===c)d=
new self.we(b,...e);else if("phaser"===c)d=new self.ye(b,...e);else if("gain"===c)d=new self.xe(b,...e);else if("stereopan"===c)d=new self.Ae(b,...e);else if("tremolo"===c)d=new self.Be(b,...e);else if("ringmod"===c)d=new self.ze(b,...e);else if("distortion"===c)d=new self.ue(b,...e);else if("compressor"===c)d=new self.re(b,...e);else if("analyser"===c)d=new self.qe(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ka.get(h);l||(l=[],g.ka.set(h,l));d.Yd=l.length;d.md=
h;l.push(d);ub(g,h)}vb(b)}
async function wb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ea()&&1===c||!e.Ea()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ka.values())for(const g of f)g.j();b.ka.clear();b.oc=a.timeScale;b.Wc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.ya=a.isSilent;b.l.Ob(b.ya);b.dc=a.masterVolume;b.Va.gain.value=
b.dc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>tb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>xb(b,f,c)));S(b)}
async function yb(b,a){try{const c=b.g.suspend(a.time);b.Xd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.l.pb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>zb(d)),b.Xd=!0);await c}catch(c){zb(c)}}
function gb(b){b.Yb||(b.Yc=!1,window.addEventListener("pointerup",b.Ba,!0),window.addEventListener("touchend",b.Ba,!0),window.addEventListener("click",b.Ba,!0),window.addEventListener("keydown",b.Ba,!0),b.Yb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ja)if(g.lb()===c)return await Db(g),g;if(f)return null;if(e&&(b.jc||b.Wd)){f=0;for(let h=0,k=b.ja.length;h<k;++h)g=b.ja[h],b.ja[f]=g,g.Ea()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.ke;e&&f&&(b.Wd=!0);c=!e||b.jc||f?new self.Ee(b,a,c,d,e,f):new self.Ce(b,a,c,d,e);b.ja.push(c);await Db(c);b.ce.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.ce.add(a));return c}
function Eb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Fb(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.fa()}function ub(b,a){a=a.toLowerCase();let c=b.fa();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.fa()):e.U(d[f+1].N())}}for(const f of Gb(b,a))e=f,d=c,e=e.ea||e.F||e.G,e.disconnect(),e.connect(d);b.Ma&&b.ed===a&&(b.Ma.disconnect(),b.Ma.connect(c))}
function*Gb(b,a){if(a)for(const c of b.H)Eb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Hb(b,a,c){return c?b.l.uf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Ib(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Eb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function kb(b,a,c,d,e,f){for(const g of b.H)if(g.lb()===c&&(g.tc()||f))return g.oa=e,g;a=await O(b,a,c,d,f);e="html5"===a.Rc?new self.De(a.v,a,e):new self.Fe(a.v,a,e);b.H.push(e);return e}
function ib(b,a){a=a.join(" ");let c=b.Fb.get(a);if(!c){let d=null;c={sd:0,promise:new Promise(e=>d=e),resolve:d};b.Fb.set(a,c)}c.sd++}function ob(b,a){return(b=b.Fb.get((0===a.length?b.ae:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Ua.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Jb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function vb(b){b.bd||(b.bd=!0,Promise.resolve().then(()=>Kb(b)))}
function Kb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.kb());m(b,"fxstate",{fxstate:a});b.bd=!1}
async function xb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await kb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.bb[0]=f[0],b.bb[1]=f[1],b.bb[2]=f[2],f=d.orient,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],e.setPosition(...b.bb),e.setOrientation(...b.ab),b.ua[0]=d.cia,b.ua[1]=d.coa,b.ua[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.sa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),mb(b,d));c.Play(k,l,q,0);a.isPlaying||c.ob();c.Kc(a)}}}function zb(b){console.error("[Audio] Offline rendering error: ",b)}
self.jb=class extends self.Da{constructor(b){super(b,"audio");this.Va=this.g=null;this.Yb=this.Yc=!1;this.Ba=()=>{if(!this.Yc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Yb&&(this.Yc=!0,window.removeEventListener("pointerup",this.Ba,!0),window.removeEventListener("touchend",this.Ba,!0),window.removeEventListener("click",this.Ba,!0),window.removeEventListener("keydown",
this.Ba,!0),this.Yb=!1)}};this.ja=[];this.H=[];this.R=null;this.ae=[];this.ce=new Set;this.be=-1;this.Fb=new Map;this.dc=1;this.ya=!1;this.od=0;this.oc=1;this.Wc=0;this.ee="HRTF";this.Pd="inverse";this.fe=600;this.de=1E4;this.he=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Wd=this.jc=!1;this.ke=this.l.Ne();this.ka=new Map;this.Ua=new Set;this.Xd=this.bd=!1;this.ed="";this.Ma=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ma&&this.Ma.disconnect();this.ed=c.toLowerCase();this.Ma=this.g.createMediaStreamSource(a);
this.Ma.connect(Fb(this,this.ed))};this.Vb=null;self.C3Audio_GetOutputStream=()=>{this.Vb||(this.Vb=this.g.createMediaStreamDestination(),this.Va.connect(this.Vb));return this.Vb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>fb(this,a)],["play",a=>hb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Fa()}],["stop-all",()=>{for(const a of this.H)a.Fa()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.ob():d.Nb();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>nb(this,a)],["set-master-volume",a=>{this.dc=a.vol;this.Va.gain.value=this.dc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Lb(d,a)}],["set-silent",a=>{this.ya=a.isSilent;this.l.Ob(this.ya);for(const c of this.H)c.Tb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.Dc(a)}],["set-playback-rate",a=>pb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),mb(d,a)}],["seek",a=>qb(this,a)],["preload",a=>rb(this,a)],["unload",a=>sb(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Ec(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>tb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);vb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ka.delete(a);ub(this,a)}}],["tick",a=>{this.oc=a.timeScale;this.Wc=a.gameTime;this.be=a.tickCount;if(0!==this.od)for(var c of this.H)c.Ia();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.sa===a&&lb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>wb(this,a)],["offline-render-audio",a=>yb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}fa(){return this.Va}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.fa()}Mb(){return this.ya}Ga(b){this.l.Ga(b)}Ra(b){this.l.Ra(b)}Sa(){for(var b of this.Ua)b.Sa();
b=this.g.currentTime;for(var a of this.H)a.Sa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.kb());m(this,"state",{tickCount:this.be,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ua].map(c=>({tag:c.md,index:c.Yd,peak:c.cb,rms:c.ge,binCount:c.m.frequencyBinCount,freqBins:c.Ud}))});0===a.length&&0===this.Ua.size&&this.Zb&&(this.l.Jd(this.le),this.Zb=!1)}static Ve(b){return b*eb}static xd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Qe(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.qa.Pa(self.jb);"use strict";function Db(b){b.bc||(b.bc=b.Jc());return b.bc}self.td=class{constructor(b,a,c,d,e){this.v=b;this.Af=a;this.Na=c;this.T=d;this.wf=e;this.Rc="";this.bc=null}j(){this.bc=this.v=null}Jc(){}V(){return this.v.V()}yc(){return this.Af}lb(){return this.Na}vc(){return this.T}Ea(){return this.wf}ga(){}};"use strict";
self.Ce=class extends self.td{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Rc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Ab=this.Bb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Eb=this.V().createGain();this.Db=null;this.L.addEventListener("canplay",()=>{this.Bb&&(this.Bb(),this.Ab=this.Bb=null);!this.Db&&this.L&&(this.Db=this.V().createMediaElementSource(this.L),this.Db.connect(this.Eb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Na}' error: `,f);this.Ab&&(this.Ab(f),this.Ab=this.Bb=null)})}j(){Ib(this.v,this);this.Eb.disconnect();this.Eb=null;this.Db.disconnect();this.Db=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Jc(){return new Promise((b,a)=>{this.Bb=b;this.Ab=a;this.L.src=this.Na})}W(){return this.L}ga(){return this.L.duration}};"use strict";
async function Mb(b){if(b.Ka)return b.Ka;var a=b.v.l;if("cordova"===a.u&&a.Ad(b.Na)&&a.$b)b.Ka=await a.Lb(b.Na);else{a=await fetch(b.Na);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ka=await a.arrayBuffer()}}async function Nb(b){if(b.ia)return b.ia;b.ia=await Hb(b.v,b.Ka,b.zf);b.Ka=null}
self.Ee=class extends self.td{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Rc="webaudio";this.ia=this.Ka=null;this.zf=!!f}j(){Ib(this.v,this);this.ia=this.Ka=null;super.j()}async Jc(){try{await Mb(this),await Nb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Na}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Ob=0;
function P(b,a){a=!!a;b.xb!==a&&(b.xb=a,b.xb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.ee,b.F.distanceModel=b.v.Pd,b.F.refDistance=b.v.fe,b.F.maxDistance=b.v.de,b.F.rolloffFactor=b.v.he),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.fa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.fa())))}
function Q(b,a){a=!!a;b.ac!==a&&(b.ac=a,b.ac?(P(b,!1),b.ea=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ea),b.ea.connect(b.fa())):(b.ea.disconnect(),b.ea=null,b.G.disconnect(),b.G.connect(b.fa())))}function mb(b,a){b.ac&&b.ld!==a&&(b.ea.pan.value=a,b.ld=a)}function T(b,a){b.Oa=a;b.G.gain.cancelScheduledValues(0);b.Ya=-1;b.G.gain.value=b.zc()}function Lb(b,a){a=!!a;b.xa!==a&&(b.xa=a,b.Tb())}
function lb(b,a,c,d,e){if(b.xb){var f=b.bb,g=b.ab,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.cd?b.v.Wc:performance.now()/1E3}
self.ud=class{constructor(b,a,c){this.v=b;this.P=a;this.oa=c;this.Ub=Ob++;this.G=this.V().createGain();this.G.connect(this.fa());this.F=null;this.xb=!1;this.bb=[0,0,0];this.ab=[0,0,0];this.ua=[0,0,0];this.ea=null;this.ac=!1;this.ld=0;this.I=!0;this.Y=this.va=this.J=!1;this.Oa=1;this.xa=!1;this.ma=1;b=this.v.od;this.cd=1===b&&!this.Ea()||2===b;this.Ya=this.sa=-1;this.je=!1}j(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.ea&&(this.ea.disconnect(),this.ea=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}fa(){return Fb(this.v,0<this.oa.length?this.oa[0]:"")}yc(){return this.P.yc()}lb(){return this.P.lb()}vc(){return this.P.vc()}Ea(){return this.P.Ea()}O(){}tc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Qa(){}ga(){return this.P.ga()}Play(){}Fa(){}ob(){}Nb(){}Sa(b){-1!==this.Ya&&b>=this.Ya&&(this.Ya=-1,this.je&&this.Fa(),Jb(this.v,"fade-ended",this.oa,this.Ub))}zc(){const b=this.Oa;return isFinite(b)?b:0}Mb(){return this.v.Mb()}Tb(){}Dc(){}Ia(){}Cc(){}Ec(){}Ac(){}kb(){var b=
this.Ub,a=this.oa,c=this.ga(),d=-1===this.Ya?this.Oa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.bb,orient:this.ab,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.sa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Qa(),playbackRate:this.ma,uid:this.sa,bufferOriginalUrl:this.yc(),bufferUrl:"",bufferType:this.vc(),isMusic:this.Ea(),isLooping:this.Y,isMuted:this.xa,resumePosition:this.Ac(),pan:f,stereoPan:this.ea?
this.ld:null}}Kc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ia());Lb(this,b.isMuted)}};"use strict";
self.De=class extends self.ud{constructor(b,a,c){super(b,a,c);this.P.Eb.connect(this.G);this.P.onended=()=>this.Mc()}j(){this.Fa();this.P.Eb.disconnect();super.j()}W(){return this.P.W()}Mc(){this.I=!0;this.sa=-1;Jb(this.v,"ended",this.oa,this.Ub)}O(){return this.W().ended}tc(){return this.I?!0:this.O()}Qa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);this.xa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.lb()}' to position '${c}': `,e)}this.v.Ga(d);this.J=this.I=!1;this.Y=b;this.ma=1}Fa(){const b=this.W();b.paused||b.pause();this.v.Ra(b);this.I=!0;this.J=!1;this.sa=-1}ob(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.Ra(b);this.J=!0}}Nb(){!this.J||this.I||this.O()||(this.v.Ga(this.W()),this.J=!1)}Tb(){this.W().muted=this.xa||this.Mb()}Dc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ia(){let b=this.ma;this.cd&&(b*=this.v.oc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Cc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}Ac(){return this.Qa()}Ec(b){b?this.IsPlaying()?(this.W().pause(),this.va=!0):this.va=!1:this.va&&(this.v.Ga(this.W()),this.va=!1)}};"use strict";
function V(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.qb=null}
self.Fe=class extends self.ud{constructor(b,a,c){super(b,a,c);this.s=null;this.fc=d=>this.Mc(d);this.Xc=!0;this.qb=null;this.S=this.ic=this.kc=0;this.gd=1}j(){this.Fa();V(this);this.fc=null;super.j()}Mc(b){this.J||this.va||b.target!==this.qb||(this.I=this.Xc=!0,this.sa=-1,V(this),Jb(this.v,"ended",this.oa,this.Ub))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Xc}tc(){return!this.s||this.I?!0:this.O()}Qa(){let b;b=this.J?this.S:this.ic+(U(this)-this.kc)*this.ma;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.xa=!1;this.gd=1;T(this,a);V(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ia;this.s.connect(this.G);this.qb=this.s;this.s.onended=this.fc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Xc=!1;this.Y=b;this.ma=1;this.kc=U(this);this.ic=c}Fa(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.sa=-1}ob(){this.J||this.I||this.O()||(this.S=this.Qa(),this.Y&&(this.S%=this.ga()),this.J=!0,this.s.stop(0))}Nb(){!this.J||this.I||this.O()||(V(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,T(this,this.Oa),this.Ia(),this.s.start(0,this.S),this.kc=U(this),this.ic=this.S,this.J=!1)}zc(){return super.zc()*this.gd}Tb(){this.gd=this.xa||this.Mb()?0:1;T(this,this.Oa)}Dc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ia(){let b=this.ma;this.cd&&(b*=this.v.oc);this.s&&(this.s.playbackRate.value=b)}Cc(b){this.I||this.O()||(this.J?this.S=b:(this.ob(),
this.S=b,this.Nb()))}Ac(){return this.S}Ec(b){b?this.IsPlaying()?(this.va=!0,this.S=this.Qa(),this.Y&&(this.S%=this.ga()),this.s.stop(0)):this.va=!1:this.va&&(V(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,T(this,this.Oa),this.Ia(),this.s.start(0,this.S),this.kc=U(this),this.ic=this.S,this.va=!1)}Kc(b){super.Kc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.v=b;this.g=b.V();this.Yd=-1;this.T=this.md="";this.o=null}j(){this.g=null}N(){}U(){}kb(){return{type:this.T,tag:this.md,params:this.o}}}
self.ve=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,X(this,this.D.gain,a,c,d)}}};
self.te=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.Cb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=W(this);this.vb.gain.value=c;this.A.connect(this.Cb);this.A.connect(this.h);this.Cb.connect(this.i);this.Cb.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Cb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Cb.disconnect();
this.X.disconnect();this.vb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.jb.xd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);X(this,this.vb.gain,e(a),c,d);break;case 5:this.o[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.se=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Od=this.Nd="";this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.A.connect(this.ub);this.A.connect(this.h);this.ub.connect(this.i)}j(){this.A.disconnect();this.ub.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}kb(){const b=super.kb();b.bufferOriginalUrl=this.Nd;b.bufferUrl="";b.bufferType=this.Od;return b}};
self.we=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.wb=W(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=W(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.wb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;X(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;X(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,X(this,this.wb.gain,a/100,c,d)}}};
self.ye=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=W(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;X(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,X(this,this.C.frequency,a,c,d)}}};self.xe=class extends Y{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=W(this);this.m.gain.value=a}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.jb.xd;switch(b){case 4:this.o[0]=e(a),X(this,this.m.gain,e(a),c,d)}}};
self.Ae=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,X(this,this.m.pan,a,c,d)}}};
self.Be=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=W(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=W(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;X(this,this.m.gain,1-a/2,c,d);X(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.ze=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Hb=W(this);this.Hb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Hb.gain);this.C.start(0);this.A.connect(this.Hb);this.A.connect(this.h);this.Hb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Hb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.ue=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=W(this);this.mc=W(this);this.lc=W(this);b=d;.01>b&&(b=.01);this.mc.gain.value=b;this.lc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.pc=this.g.createWaveShaper();this.Sc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Sc[32768+e]=f,this.Sc[32768-
e-1]=-f;this.pc.curve=this.Sc;this.A.connect(this.mc);this.A.connect(this.h);this.mc.connect(this.pc);this.pc.connect(this.lc);this.lc.connect(this.i)}j(){this.A.disconnect();this.mc.disconnect();this.pc.disconnect();this.lc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.re=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.qe=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.Ud=new Float32Array(this.m.frequencyBinCount);this.ie=new Uint8Array(a);this.ge=this.cb=0;b=this.v;b.Ua.add(this);S(b)}j(){this.v.Ua.delete(this);this.m.disconnect();super.j()}Sa(){this.m.getFloatFrequencyData(this.Ud);this.m.getByteTimeDomainData(this.ie);const b=this.m.fftSize;let a=this.cb=0;for(var c=0;c<b;++c){let d=(this.ie[c]-
128)/128;0>d&&(d=-d);this.cb<d&&(this.cb=d);a+=d*d}c=self.jb.Qe;this.cb=c(this.cb);this.ge=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};"use strict";let Z=null,Pb=null;window.addEventListener("beforeinstallprompt",b=>{b.preventDefault();Z=b;Pb&&m(Pb,"install-available");return!1});function Qb(){}function Rb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function Sb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}async function Tb(){if(!Z)return{result:"unavailable"};try{return Z.prompt(),{result:(await Z.userChoice).outcome}}catch(b){return console.error("[Construct] Requesting install failed: ",b),{result:"failed"}}}
self.qa.Pa(class extends self.Da{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Rb(this)],["alert",a=>this.Lc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Nc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Sb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.l.pa()?window.open(c,"_blank"):this.Sf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.l.pa()||"macos-wkwebview"===this.u)self.qa.Sb(!0),this.l.Ha({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Qb)}}],["exit-fullscreen",()=>{if(this.l.pa()||"macos-wkwebview"===this.u)self.qa.Sb(!1),this.l.Ha({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Qb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}],["request-install",()=>Tb()]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}sc(){Z?m(this,"install-available"):Pb=this;window.addEventListener("appinstalled",
()=>{m(this,"app-installed")})}Lc(b){alert(b.message)}Nc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";async function Ub(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}
self.qa.Pa(class extends self.Da{constructor(b){super(b,"localstorage");v(this,[["init",()=>this.Pb()],["request-persistent",()=>Ub()]])}async Pb(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});"use strict";
self.qa.Pa(class extends self.Da{constructor(b){super(b,"avix-pokisdk-forc3");this.Vc=this.Xb=this.da=!1;v(this,[["InitPoki",this.Ke.bind(this)],["NotifyGameplayStart",this.Re.bind(this)],["NotifyGameplayStop",this.Bc.bind(this)],["HappyTime",this.Je.bind(this)],["RequestCommercialBreak",this.Se.bind(this)],["RequestRewardedBreak",this.Te.bind(this)],["SetDebugMode",this.Dd.bind(this)],["GameLoadingFinished",this.He.bind(this)]])}He(){this.da&&!this.Vc&&(this.Vc=!0,globalThis.PokiSDK.gameLoadingFinished())}Re(){this.da&&
(this.Vc||console.log("Don't forget to send the Loading Finished Notification, or configure the Poki Plugin to manage it automatically."),this.Xb=!0,globalThis.PokiSDK.gameplayStart())}Bc(){this.da&&(this.Xb=!1,globalThis.PokiSDK.gameplayStop())}Je({Vf:b}){this.da&&globalThis.PokiSDK.happyTime(b)}Se(){if(!this.da)return{result:!1,Kb:!1};this.Xb&&this.Bc();m(this,"SuspendRuntime");return globalThis.PokiSDK.commercialBreak().then(()=>{m(this,"ResumeRuntime");return{result:!0,Kb:!1}}).catch(b=>{console.error(b);
return{result:!1,Kb:b}})}Te(){if(!this.da)return{result:!1,Kb:!1};this.Xb&&this.Bc();m(this,"SuspendRuntime");return globalThis.PokiSDK.rewardedBreak().then(b=>{m(this,"ResumeRuntime");return{result:b,Kb:!1}}).catch(b=>{console.error(b);return{result:!1,Kb:b}})}Dd({enable:b}){this.da&&globalThis.PokiSDK.setDebug(b)}Ke({Tf:b,preventScroll:a}){if("undefined"!==typeof globalThis.PokiSDK){a&&this.preventScroll();this.da=!0;let c=!1;return globalThis.PokiSDK.init().then(()=>{console.log("Poki SDK successfully initialized");
return{loaded:this.da,oe:c}}).catch(()=>{console.log("Initialized, but the user likely has adblock");c=!0;return{loaded:this.da,oe:c}}).finally(()=>{b&&this.Dd(!0);globalThis.PokiSDK.gameLoadingStart()})}console.log("Poki SDK failed to load");return Promise.resolve({loaded:this.da,oe:!1})}preventScroll(){window.addEventListener("keydown",b=>{["ArrowDown","ArrowUp"," "].includes(b.key)&&b.preventDefault()});window.addEventListener("wheel",b=>b.preventDefault(),{passive:!1})}});
