function m(b,a,c,d){b.j.ob(b.sb,a,c,d)}function n(b,a,c,d){b.j.ba?m(b,a,c,d):b.j.Qe()._OnMessageFromDOM({type:"event",component:b.sb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.j.B(b.sb,a,c)}function v(b,a){for(const [c,d]of a)p(b,c,d)}function w(b){b.Wb||(b.j.Bc(b.ge),b.Wb=!0)}window.Ca=class{constructor(b,a){this.j=b;this.sb=a;this.Wb=!1;this.ge=()=>this.Ra()}pc(){}Ra(){}};
window.Df=class{constructor(){this.kd=-1}l(){-1!==this.kd&&(self.clearTimeout(this.kd),this.kd=-1)}};"use strict";function ba(b,a){p(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}function x(b,a){b=b.Wa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Ub}
window.rd=class extends self.Ca{constructor(b,a){super(b,a);this.Wa=new Map;this.qb=!0;v(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=x(this,c);this.qb&&d.parentElement.removeChild(d);this.Wa.delete(c)}],["set-visible",c=>{if(this.qb){var d=this.Wa.get(c.elementId),e=d.Ub;d.Qd?e.style.display=c.isVisible?"":"none":d.jf=!!c.isVisible}}],["update-position",c=>{if(this.qb){var d=this.Wa.get(c.elementId),e=d.Ub,f=this.j;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.pf=g;g=f.td(g);g!==d.Ia&&(e.remove(),f.uc(g).appendChild(e),d.Ia=g,f.Mc());c=c.htmlZIndex;c!==d.Uc&&(d.Uc=c,f.Mc());d.Qd||(d.Qd=!0,d.jf&&(e.style.display=""))}}],["update-state",c=>{x(this,c.elementId);throw Error("required override");}],["focus",c=>this.Jc(c)],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,
c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}Jc(b){var a=x(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ea=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.tf?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.xf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function fa(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let A=new Audio;
const ha={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ia(b){b=await ja(b);return(new TextDecoder("utf-8")).decode(b)}
function ja(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let D=0;window.RealFile=window.File;const E=[],G=new Map,H=new Map;let ka=0;const la=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");la.push(b)};const ma=new Set(["cordova","playable-ad","instant-games"]);let ra=!1;
window.pa=class b{constructor(a){this.ba=a.zf;this.ya=null;this.aa="";this.eb=a.wf;this.Ib={};this.Ya=this.va=null;this.Va=[];this.ma=null;this.Ud=!0;this.M=[];this.dd=[];this.ed=!1;this.he=()=>this.Oe();this.Wc=!1;this.Nd=0;this.xb=null;this.cb=-1;this.nf=()=>this.Ze();this.Fb=new Set;this.ld=null;this.ie=[];this.u=a.je;this.Xb="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.ba=!1;da&&(this.ba=!1);if("cordova"===this.u&&this.ba&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.oa()?self.chrome.webview.addEventListener("message",c=>this.Dd(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Dd(c));this.$b=this.sa=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.cf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Ue());this.B("runtime","cordova-fetch-local-file",c=>this.Ve(c));this.B("runtime","create-job-worker",()=>this.We());this.B("runtime","send-wrapper-extension-message",c=>this.bf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Nb(a)):this.Nb(a)}l(){this.Cc();this.ya&&(this.ya=this.ya.onmessage=null);this.va&&(this.va.terminate(),this.va=null);this.Ya&&(this.Ya.l(),this.Ya=null);for(const {canvas:a,
hb:c}of this.M)a.remove(),c.remove();this.M.length=0}ud(){return this.M[0].canvas}td(a){return Math.min(a,this.M.length-1)}uc(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].hb}Ee(){return ca&&"cordova"===this.u}mb(){const a=navigator.userAgent;return ca&&ma.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Ce(){return y}vd(){return y&&ma.has(this.u)}xd(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}oa(){return this.xd()||"xbox-uwp-webview2"===this.u}async Nb(a){this.ba&&!await fa()&&(this.ba=!1);"macos-wkwebview"===this.u?this.Ga({type:"ready"}):this.oa()&&(this.ef(),this.ie=(await this.Te()).registeredComponentIds);if("playable-ad"===this.u){this.sa=self.c3_base64files;this.$b={};await this.Le();for(let d=0,e=a.gb.length;d<e;++d){var c=a.gb[d];this.$b.hasOwnProperty(c)?a.gb[d]={tf:!0,xf:this.$b[c]}:this.sa.hasOwnProperty(c)&&(a.gb[d]=URL.createObjectURL(this.sa[c]))}a.oc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Bc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.vf?this.aa=a.vf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Bf&&(this.Ib=a.Bf);c=new MessageChannel;this.ya=c.port1;this.ya.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ye(d));this.xb=
new self.Fe(this);await sa(this.xb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.Se(a,c.port2):await this.Re(a,c.port2)}Ec(a){a=this.Ib.hasOwnProperty(a)?this.Ib[a]:a.endsWith("/workermain.js")&&this.Ib.hasOwnProperty("workermain.js")?this.Ib["workermain.js"]:"playable-ad"===
this.u&&this.sa.hasOwnProperty(a)?this.sa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async rc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.Xb)return a=await this.Jb(d.sf?a:this.eb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}qa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}tc(){return this.oa()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.u)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Bd(a){var c=this.aa,d=location.href,e=this.qa(),f=this.ga(),g=this.tc(),
h=window.devicePixelRatio,k=b.lb(),l=a.Hf,q=window.cr_previewImageBlobs||this.sa,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.je;var aa=(new URLSearchParams(self.location.search)).has("debug"),F=this.xb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:q,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,exportType:a,isDebug:aa,
ife:!!self.Gf,jobScheduler:{inputPort:F.Vc,outputPort:F.cd,maxNumWorkers:F.kf},supportedAudioFormats:ha,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.eb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.eb+"opus.wasm.wasm",isFileProtocol:this.Xb,isiOSCordova:this.Ee(),isiOSWebView:this.mb(),isWindowsWebView2:this.xd(),isAnyWebView2Wrapper:this.oa(),wrapperComponentIds:this.ie,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Se(a,c){const d=this.Ec(a.Af);"preview"===
this.u?(this.va=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,q)=>{const r=t=>{this.va.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():q()};this.va.addEventListener("message",r);this.va.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.va=await this.rc(d,this.aa,{type:"module",name:"Runtime",sf:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);
const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,hb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.oc||[],k=a.gb;h=await Promise.all(h.map(l=>this.Sa(l)));k=await Promise.all(k.map(l=>this.Sa(l)));if("cordova"===this.u)for(let l=0,q=a.nc.length;l<q;++l){const r=a.nc[l],t=r[0];if(t===a.md||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Sa(t)}this.va.postMessage(Object.assign(this.Bd(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.nc,mainProjectScript:a.md,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...ta(this.xb)]);this.Va=E.map(l=>new l(this));this.Ad();ua(e);va(g);wa(this.ma);self.c3_callFunction=(l,q)=>{var r=this.ma;return r.j.yd(r.sb,"js-invoke-function",{name:l,params:q})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.ob("runtime","go-to-last-error-script"))}async Re(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,hb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Va=E.map(h=>new h(this));this.Ad();ua(d);va(e);e=a.gb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.oc)){var f=[...a.oc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Sa(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.md;const g=a.nc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Sa(k),await z(k),"preview"!==this.u||e[h]||this.Fd(h,"main script did not run to completion")}catch(l){this.Fd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Sa(k),await z(k);"preview"===this.u&&"object"!==typeof self.Cf.Ef?(this.Pb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Bd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:la}),wa(this.ma),this.Cd(),this.Ya=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ya,a))}Fd(a,c){this.Pb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Cd(){this.Pb()}Pb(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async We(){const a=await xa(this.xb);return{outputPort:a,transferables:[a]}}cf(a){if(!this.Wc){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,hb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Ud&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Ud=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,hb:q}=this.M.pop();q.remove();this.ba&&!d?this.dd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,q=c-this.M.length;l<q;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,ua(c),va(d),this.M.push({canvas:c,hb:d});for(const l of this.Va)if(l instanceof window.rd&&l.qb)for(const q of l.Wa.values())e=l.j.td(q.pf),f=q.Ia,-1!==
e&&-1!==f&&e!==f&&(f=q.Ub,f.remove(),l.j.uc(e).appendChild(f),q.Ia=e);this.Mc();return{addedCanvases:a,transferables:k}}Ue(){for(const a of this.dd)a.remove();this.dd.length=0}Mc(){this.ed||(this.ed=!0,this.Bc(this.he))}Oe(){this.Ed(this.he);this.ed=!1;let a=[];for(var c of this.Va)if(c instanceof window.rd){var d=c.qb?[...c.Wa.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ia,l=h.Ia;return k!==l?k-l:g.Uc-h.Uc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ia!==c&&(this.zd(c,a.slice(d,
e)),c=g.Ia,d=e)}d<e&&this.zd(c,a.slice(d,e))}zd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Ub);var d=new Set(c);a=this.uc(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Qe(){if(this.ba)throw Error("not available in worker mode");return this.Ya}ob(a,c,d,e,f){this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}yd(a,c,d,e,f){const g=ka++,h=new Promise((k,l)=>{H.set(g,{resolve:k,reject:l})});this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Xe(a);if("result"===c)this.$e(a);else if("runtime-ready"===c)this.af();else if("alert-error"===c)this.Pb(),alert(a.message);else if("creating-runtime"===c)this.Cd();else throw Error(`unknown message '${c}'`);}Xe(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Ob(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Ob(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Ob(f,!1,""+h)}):this.Ob(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Ob(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.ya.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}$e(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Oa(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Ad(){for(const a of this.Va)if("runtime"===a.sb){this.ma=a;return}throw Error("cannot find runtime DOM handler");
}Ye(a){this.ob("debugger","message",a)}af(){for(const a of this.Va)a.pc()}static lb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ra)}static Qb(a){ra=!!a}Bc(a){this.Fb.add(a);this.Lc()}Ed(a){this.Fb.delete(a);0===this.Fb.size&&this.Cc()}Lc(){-1===this.cb&&0<this.Fb.size&&(this.cb=requestAnimationFrame(this.nf))}Cc(){-1!==this.cb&&(cancelAnimationFrame(this.cb),this.cb=-1)}Ze(){this.cb=-1;for(const a of this.Fb)a();this.Lc()}Fa(a){this.ma.Fa(a)}Qa(a){this.ma.Qa(a)}Kc(){this.ma.Kc()}Mb(a){this.ma.Mb(a)}De(){return!!ha["audio/webm; codecs=opus"]}async ff(a){a=
await this.yd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}He(a){this.Wc=!0;this.Nd=a}Be(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}wd(a){return!this.Be(a)}async Sa(a){return"cordova"===this.u&&(a.startsWith("file:")||this.Xb&&this.wd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Jb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ve(a){const c=a.filename;switch(a.as){case "text":return await this.Ae(c);
case "buffer":return await this.Jb(c);default:throw Error("unsupported type");}}qd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ae(a){a=await this.qd(a);return await ia(a)}Dc(){if(C.length&&!(8<=D)){D++;var a=C.shift();this.Me(a.filename,a.yf,a.rf)}}Jb(a){return new Promise((c,d)=>{C.push({filename:a,yf:e=>{D--;this.Dc();c(e)},rf:e=>{D--;this.Dc();d(e)}});this.Dc()})}async Me(a,c,d){try{const e=
await this.qd(a),f=await ja(e);c(f)}catch(e){d(e)}}Dd(a){if("entered-fullscreen"===a)b.Qb(!0),I(this.ma);else if("exited-fullscreen"===a)b.Qb(!1),I(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.ld(a),this.ld=null):"extension-message"===c?this.ob("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}bf(a){this.Ga({type:"extension-message",componentId:a.componentId,messageId:a.messageId,
params:a.params||[],asyncId:a.asyncId})}Ga(a){this.oa()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}ef(){window.moveTo=(a,c)=>{this.Ga({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ga({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Te(){return this.oa()?new Promise(a=>{this.ld=a;this.Ga({type:"wrapper-init"})}):
Promise.resolve()}async Le(){const a=[];for(const [c,d]of Object.entries(this.sa))a.push(this.Ke(c,d));await Promise.all(a)}async Ke(a,c){if("object"===typeof c)this.sa[a]=new Blob([c.str],{type:c.type}),this.$b[a]=c.str;else{let d=await this.Pe(c);d||(d=this.Ne(c));this.sa[a]=d}}async Pe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Ne(a){a=this.df(a);return this.Je(a.data,a.uf)}df(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{uf:a,data:d}}Je(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const J=self.pa,ya=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},za={dispatchUserScriptEvent:!0},Aa={dispatchRuntimeEvent:!0};function Ba(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Da(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Ea(b){b=URL.createObjectURL(b);try{return await Da(b)}finally{URL.revokeObjectURL(b)}}function Fa(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ga=new Set(["input","textarea","datalist","select"]),Ha=new Set(["canvas","body","html"]);
function L(b){b.target.tagName&&Ha.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ia(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ja(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Ea(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ea(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ka=!1;document.addEventListener("pause",()=>Ka=!0);document.addEventListener("resume",()=>Ka=!1);function ua(b){b.addEventListener("selectstart",L);b.addEventListener("gesturehold",L);b.addEventListener("pointerdown",L)}function va(b){b.addEventListener("selectstart",Ia);b.addEventListener("gesturehold",Ia);b.addEventListener("touchstart",Ia)}function wa(b){b.Md=!0;b.Zc=b.j.qa();b.yb=b.j.ga()}
function I(b){if(!b.ka){var a=J.lb();a&&"any"!==b.hd&&La(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ga()})}}async function Ma(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Na(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Oa(b){return await self.C3_GetSvgImageSize(b.blob)}function Pa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Qa(b){self.setTimeout(()=>{b.Ld=!0},1E3);"cordova"===b.j.u?(document.addEventListener("pause",()=>Ra(b,!0)),document.addEventListener("resume",()=>Ra(b,!1))):document.addEventListener("visibilitychange",()=>Ra(b,"hidden"===document.visibilityState));b.dc=!("hidden"!==document.visibilityState&&!Ka);return{isSuspended:b.dc}}
function Sa(b){b.Hd||(b.Hd=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ta(b){b.Gd||(b.Gd=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Ua(b){await Ba(b.url)}
function Va(b,a){b.Od=a.message;-1===b.Qc&&(b.Qc=setTimeout(()=>{b.Qc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Od)},250))}function Wa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.lb(),innerWidth:b.qa(),innerHeight:b.ga()})}
function Ra(b,a){b.dc!==a&&((b.dc=a)?b.j.Cc():b.j.Lc(),m(b,"visibilitychange",{hidden:a}),!a&&b.j.mb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Xa(b,a,c){"Backspace"===c.key&&L(c);"nwjs"===b.j.u&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.ka){var d=ya.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K)}}
function M(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Ba,pageX:c.pageX,pageY:c.pageY+b.Ba,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.ad);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Ba,pageX:c.pageX,pageY:c.pageY+b.Ba,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.ad=c.buttons)}}function Ya(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Ba=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Ba=a))}}
function Za(b,a,c,d){const e=b.qa(),f=b.ga();b.fb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.lb(),cssDisplayMode:b.j.tc()}):10>d&&$a(b,e,f,d+1)}function $a(b,a,c,d){-1!==b.fb&&clearTimeout(b.fb);b.fb=setTimeout(()=>Za(b,a,c,d),48)}
function La(b){b=b.hd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function ab(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Oa(class extends self.Ca{constructor(b){super(b,"runtime");this.Md=!1;this.fb=-1;this.hd="any";this.dc=this.Gd=this.Hd=!1;this.kc=document.createElement("div");this.kc.className="c3-screen-reader-text";this.kc.setAttribute("aria-live","polite");document.body.appendChild(this.kc);this.Ka=null;this.ka=!1;this.Od="";this.Qc=-1;this.Ld=!1;this.Zc=b.qa();this.yb=b.ga();this.Ba=this.Hb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ma(c));b.B("runtime","raster-svg-image",c=>Na(c));b.B("runtime","get-svg-image-size",c=>Oa(c));b.B("runtime","set-target-orientation",c=>{this.hd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Pa(c));b.B("runtime","go-to-script",c=>Pa(c));b.B("runtime","before-start-ticking",()=>Qa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ka||(this.Ka=document.createElement("div"),this.Ka.id="inspectOutline",document.body.appendChild(this.Ka));var d=this.Ka;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ka&&(this.Ka.style.display="none")});b.B("runtime","enable-device-orientation",()=>Sa(this));b.B("runtime","enable-device-motion",()=>Ta(this));b.B("runtime","add-stylesheet",c=>Ua(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Hc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.kc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.j.ud().style.display="";this.j.He(c.duration)});b.B("runtime","export-to-video-progress",c=>Va(this,c));b.B("runtime","exported-to-video",c=>{window.qf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.qf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Fa(d)||c.preventDefault()});window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});window.addEventListener("pointerdown",L,{passive:!1});this.ad=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ja,{passive:!1});window.addEventListener("wheel",Ja,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Md){var c=this.qa();var d=this.ga();if(this.j.vd()){if(this.Ld){if(this.Zc===
c&&d<this.yb){this.Hb=this.yb-d;Ya(this,this.yb,this.Hb);c=void 0;break a}0<this.Hb&&(this.Hb=0,Ya(this,d,this.Hb))}this.Zc=c;this.yb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.lb(),cssDisplayMode:this.j.tc()});this.j.mb()&&(-1!==this.fb&&clearTimeout(this.fb),Za(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",
()=>I(this));window.addEventListener("fullscreenerror",c=>Wa(this,c));window.addEventListener("webkitfullscreenerror",c=>Wa(this,c));window.addEventListener("mozfullscreenerror",c=>Wa(this,c));if(b.mb()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.Za=new Set;this.bc=new WeakSet;this.xa=!1}pc(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Aa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},Aa);this.ad=0});window.addEventListener("focusin",a=>{a=a.target;(Ga.has(a.tagName.toLowerCase())||Fa(a))&&m(this,"keyboard-blur",null,Aa)});window.addEventListener("keydown",a=>Xa(this,"keydown",a));window.addEventListener("keyup",a=>Xa(this,"keyup",a));window.addEventListener("mousedown",a=>M(this,"mousedown",a,
za));window.addEventListener("mousemove",a=>M(this,"mousemove",a,za));window.addEventListener("mouseup",a=>M(this,"mouseup",a,za));window.addEventListener("dblclick",a=>M(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Ba,pageX:a.pageX,pageY:a.pageY+this.Ba,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
ab(a.target)&&document.activeElement&&!ab(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.j.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Kc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.j.Ce()&&!this.j.vd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Ya(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.j.mb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}qa(){return this.j.qa()}ga(){return this.j.ga()}Kc(){var b=
[...this.Za];this.Za.clear();if(!this.xa)for(const a of b)(b=a.play())&&b.catch(()=>{this.bc.has(a)||this.Za.add(a)})}Fa(b){if("function"!==typeof b.play)throw Error("missing play function");this.bc.delete(b);let a;try{a=b.play()}catch(c){this.Za.add(b);return}a&&a.catch(()=>{this.bc.has(b)||this.Za.add(b)})}Qa(b){this.Za.delete(b);this.bc.add(b)}Mb(b){this.xa=!!b}Hc(b){alert(b.message)}});"use strict";
async function sa(b){if(b.gf)throw Error("already initialised");b.gf=!0;var a=b.za.Ec(("playable-ad"===b.za.u?b.za.eb:"")+"dispatchworker.js");b.Pc=await b.za.rc(a,b.rb,{name:"DispatchWorker"});a=new MessageChannel;b.Vc=a.port1;b.Pc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.cd=await xa(b)}function ta(b){return[b.Vc,b.cd]}
async function xa(b){const a=b.Vd.length;var c=b.za.Ec(("playable-ad"===b.za.u?b.za.eb:"")+"jobworker.js");c=await b.za.rc(c,b.rb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Pc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Vd.push(c);return e.port1}
self.Fe=class{constructor(b){this.za=b;this.rb=b.aa;this.rb="preview"===b.u?this.rb+"workers/":this.rb+b.eb;this.kf=Math.min(navigator.hardwareConcurrency||2,16);this.Pc=null;this.Vd=[];this.cd=this.Vc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.pa({zf:!1,Af:"workermain.js",gb:["scripts/c3runtime.js"],nc:[],md:"",wf:"scripts/",oc:[],je:"html5"}));"use strict";let O=null,bb=null;
window.addEventListener("beforeinstallprompt",b=>{b.preventDefault();O=b;bb&&m(bb,"install-available");return!1});function cb(){}function db(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function eb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}async function fb(){if(!O)return{result:"unavailable"};try{return O.prompt(),{result:(await O.userChoice).outcome}}catch(b){return console.error("[Construct] Requesting install failed: ",b),{result:"failed"}}}
self.pa.Oa(class extends self.Ca{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
db(this)],["alert",a=>this.Hc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Jc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>eb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.j.oa()?window.open(c,"_blank"):this.Ff||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.j.oa()||"macos-wkwebview"===this.u)self.pa.Qb(!0),this.j.Ga({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(cb)}}],["exit-fullscreen",()=>{if(this.j.oa()||"macos-wkwebview"===this.u)self.pa.Qb(!1),this.j.Ga({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(cb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}],["request-install",()=>fb()]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}pc(){O?m(this,"install-available"):bb=this;window.addEventListener("appinstalled",
()=>{m(this,"app-installed")})}Hc(b){alert(b.message)}Jc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
self.pa.Oa(class extends self.Ca{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.j.ud().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function gb(b,a){a=a.type;let c=!0;0===a?c=await hb():1===a&&(c=await jb());m(b,"permission-result",{type:a,result:c})}async function hb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function jb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.pa.Oa(class extends self.Ca{constructor(b){super(b,"touch");p(this,"request-permission",a=>gb(this,a))}});"use strict";const kb=180/Math.PI;
async function lb(b,a){if(a.isiOSCordova||a.isSafari)b.fc=!0;b.jd=a.timeScaleMode;b.$d=["equalpower","HRTF","soundfield"][a.panningModel];b.Kd=["linear","inverse","exponential"][a.distanceModel];b.ae=a.refDistance;b.Zd=a.maxDistance;b.ce=a.rolloffFactor;if(b.j.Wc)b.fc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.j.Nd)});else{var c={latencyHint:a.latencyHint};b.fe||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");mb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&mb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ua=b.g.createGain();b.Ua.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function nb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,q=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Wd=g.slice(0);ob(b,g);try{b.R=await pb(b,c,d,e,g,f);if(q){Q(b.R,!0);var u=b.R,aa=q.x,F=q.y,Db=q.z,Eb=q.angle,na=q.innerAngle,oa=q.outerAngle,qa=q.outerGain;if(u.wb){qb(u,aa,F,Db,Eb);var B=self.ib.Ie;
u.ta[0]!==B(na)&&(u.ta[0]=B(na),u.F.coneInnerAngle=B(na));u.ta[1]!==B(oa)&&(u.ta[1]=B(oa),u.F.coneOuterAngle=B(oa));u.ta[2]!==qa&&(u.ta[2]=qa,u.F.coneOuterGain=qa)}q.hasOwnProperty("uid")&&(b.R.ra=q.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),rb(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(Fb){console.error("[Construct] Audio: error starting playback: ",Fb);return}finally{c=g.join(" ");d=b.Eb.get(c);if(!d)throw Error("expected pending tag");d.nd--;0===d.nd&&(d.resolve(),b.Eb.delete(c))}w(b)}
async function sb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await tb(b,c);for(const h of S(b,c))if(!h.wa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Na=d;h.Xa=g;h.ee=a}T(b)}async function ub(b,a){const c=a.tags;a=a.rate;await tb(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Ha())}async function vb(b,a){const c=a.tags;a=a.pos;await tb(b,c);for(const d of S(b,c))d.yc(a)}
async function wb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await pb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function xb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function yb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.pe(b,...e);else if("delay"===c)d=new self.ne(b,...e);else if("convolution"===c){var g=d=new self.me(b,f.ha,...e),h=a.bufferType;g.Id=a.bufferOriginalUrl;g.Jd=h}else if("flanger"===c)d=
new self.qe(b,...e);else if("phaser"===c)d=new self.se(b,...e);else if("gain"===c)d=new self.re(b,...e);else if("stereopan"===c)d=new self.ue(b,...e);else if("tremolo"===c)d=new self.ve(b,...e);else if("ringmod"===c)d=new self.te(b,...e);else if("distortion"===c)d=new self.oe(b,...e);else if("compressor"===c)d=new self.le(b,...e);else if("analyser"===c)d=new self.ke(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Td=l.length;d.gd=
h;l.push(d);zb(g,h)}Ab(b)}
async function Bb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Da()&&1===c||!e.Da()&&2===c?d.push(e):e.l();b.H=d}for(const f of b.ja.values())for(const g of f)g.l();b.ja.clear();b.lc=a.timeScale;b.Rc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.xa=a.isSilent;b.j.Mb(b.xa);b.ac=a.masterVolume;b.Ua.gain.value=
b.ac;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>yb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Cb(b,f,c)));T(b)}
async function Gb(b,a){try{const c=b.g.suspend(a.time);b.Sd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.j.ob("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Hb(d)),b.Sd=!0);await c}catch(c){Hb(c)}}
function mb(b){b.Vb||(b.Tc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Vb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.kb()===c)return await Ib(g),g;if(f)return null;if(e&&(b.fc||b.Rd)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Da()?g.l():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.fe;e&&f&&(b.Rd=!0);c=!e||b.fc||f?new self.ye(b,a,c,d,e,f):new self.we(b,a,c,d,e);b.ia.push(c);await Ib(c);b.Yd.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Yd.add(a));return c}
function Jb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Kb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function zb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Lb(b,a))e=f,d=c,e=e.da||e.F||e.G,e.disconnect(),e.connect(d);b.La&&b.$c===a&&(b.La.disconnect(),b.La.connect(c))}
function*Lb(b,a){if(a)for(const c of b.H)Jb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Mb(b,a,c){return c?b.j.ff(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Nb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.l():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Jb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function pb(b,a,c,d,e,f){for(const g of b.H)if(g.kb()===c&&(g.qc()||f))return g.na=e,g;a=await P(b,a,c,d,f);e="html5"===a.Nc?new self.xe(a.v,a,e):new self.ze(a.v,a,e);b.H.push(e);return e}
function ob(b,a){a=a.join(" ");let c=b.Eb.get(a);if(!c){let d=null;c={nd:0,promise:new Promise(e=>d=e),resolve:d};b.Eb.set(a,c)}c.nd++}function tb(b,a){return(b=b.Eb.get((0===a.length?b.Wd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Ta.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Ob(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Ab(b){b.Xc||(b.Xc=!0,Promise.resolve().then(()=>Pb(b)))}
function Pb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.jb());m(b,"fxstate",{fxstate:a});b.Xc=!1}
async function Cb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await pb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],f=d.orient,b.$a[0]=f[0],b.$a[1]=f[1],b.$a[2]=f[2],e.setPosition(...b.ab),e.setOrientation(...b.$a),b.ta[0]=d.cia,b.ta[1]=d.coa,b.ta[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ra=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),rb(b,d));c.Play(k,l,q,0);a.isPlaying||c.nb();c.Gc(a)}}}function Hb(b){console.error("[Audio] Offline rendering error: ",b)}
self.ib=class extends self.Ca{constructor(b){super(b,"audio");this.Ua=this.g=null;this.Vb=this.Tc=!1;this.Aa=()=>{if(!this.Tc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Vb&&(this.Tc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Vb=!1)}};this.ia=[];this.H=[];this.R=null;this.Wd=[];this.Yd=new Set;this.Xd=-1;this.Eb=new Map;this.ac=1;this.xa=!1;this.jd=0;this.lc=1;this.Rc=0;this.$d="HRTF";this.Kd="inverse";this.ae=600;this.Zd=1E4;this.ce=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Rd=this.fc=!1;this.fe=this.j.De();this.ja=new Map;this.Ta=new Set;this.Sd=this.Xc=!1;this.$c="";this.La=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.La&&this.La.disconnect();this.$c=c.toLowerCase();this.La=this.g.createMediaStreamSource(a);
this.La.connect(Kb(this,this.$c))};this.Tb=null;self.C3Audio_GetOutputStream=()=>{this.Tb||(this.Tb=this.g.createMediaStreamDestination(),this.Ua.connect(this.Tb));return this.Tb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>lb(this,a)],["play",a=>nb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ea()}],["stop-all",()=>{for(const a of this.H)a.Ea()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.nb():d.Lb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>sb(this,a)],["set-master-volume",a=>{this.ac=a.vol;this.Ua.gain.value=this.ac}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Qb(d,a)}],["set-silent",a=>{this.xa=a.isSilent;this.j.Mb(this.xa);for(const c of this.H)c.Rb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.zc(a)}],["set-playback-rate",a=>ub(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),rb(d,a)}],["seek",a=>vb(this,a)],["preload",a=>wb(this,a)],["unload",a=>xb(this,a)],["unload-all",()=>{for(const a of this.ia)a.l();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Ac(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>yb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Ab(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.ja.delete(a);zb(this,a)}}],["tick",a=>{this.lc=a.timeScale;this.Rc=a.gameTime;this.Xd=a.tickCount;if(0!==this.jd)for(var c of this.H)c.Ha();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ra===a&&qb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Bb(this,a)],["offline-render-audio",a=>Gb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Ua}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Kb(){return this.xa}Fa(b){this.j.Fa(b)}Qa(b){this.j.Qa(b)}Ra(){for(var b of this.Ta)b.Ra();
b=this.g.currentTime;for(var a of this.H)a.Ra(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.jb());m(this,"state",{tickCount:this.Xd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ta].map(c=>({tag:c.gd,index:c.Td,peak:c.bb,rms:c.be,binCount:c.m.frequencyBinCount,freqBins:c.Pd}))});0===a.length&&0===this.Ta.size&&this.Wb&&(this.j.Ed(this.ge),this.Wb=!1)}static Ie(b){return b*kb}static sd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Ge(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.pa.Oa(self.ib);"use strict";function Ib(b){b.Zb||(b.Zb=b.Fc());return b.Zb}self.od=class{constructor(b,a,c,d,e){this.v=b;this.mf=a;this.Ma=c;this.T=d;this.hf=e;this.Nc="";this.Zb=null}l(){this.Zb=this.v=null}Fc(){}V(){return this.v.V()}vc(){return this.mf}kb(){return this.Ma}sc(){return this.T}Da(){return this.hf}fa(){}};"use strict";
self.we=class extends self.od{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Nc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.zb=this.Ab=null;this.L.addEventListener("canplaythrough",()=>!0);this.Db=this.V().createGain();this.Cb=null;this.L.addEventListener("canplay",()=>{this.Ab&&(this.Ab(),this.zb=this.Ab=null);!this.Cb&&this.L&&(this.Cb=this.V().createMediaElementSource(this.L),this.Cb.connect(this.Db))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ma}' error: `,f);this.zb&&(this.zb(f),this.zb=this.Ab=null)})}l(){Nb(this.v,this);this.Db.disconnect();this.Db=null;this.Cb.disconnect();this.Cb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.l()}Fc(){return new Promise((b,a)=>{this.Ab=b;this.zb=a;this.L.src=this.Ma})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Rb(b){if(b.Ja)return b.Ja;var a=b.v.j;if("cordova"===a.u&&a.wd(b.Ma)&&a.Xb)b.Ja=await a.Jb(b.Ma);else{a=await fetch(b.Ma);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ja=await a.arrayBuffer()}}async function Sb(b){if(b.ha)return b.ha;b.ha=await Mb(b.v,b.Ja,b.lf);b.Ja=null}
self.ye=class extends self.od{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Nc="webaudio";this.ha=this.Ja=null;this.lf=!!f}l(){Nb(this.v,this);this.ha=this.Ja=null;super.l()}async Fc(){try{await Rb(this),await Sb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ma}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Tb=0;
function Q(b,a){a=!!a;b.wb!==a&&(b.wb=a,b.wb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.$d,b.F.distanceModel=b.v.Kd,b.F.refDistance=b.v.ae,b.F.maxDistance=b.v.Zd,b.F.rolloffFactor=b.v.ce),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function R(b,a){a=!!a;b.Yb!==a&&(b.Yb=a,b.Yb?(Q(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.ea())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.ea())))}function rb(b,a){b.Yb&&b.fd!==a&&(b.da.pan.value=a,b.fd=a)}function U(b,a){b.Na=a;b.G.gain.cancelScheduledValues(0);b.Xa=-1;b.G.gain.value=b.wc()}function Qb(b,a){a=!!a;b.wa!==a&&(b.wa=a,b.Rb())}
function qb(b,a,c,d,e){if(b.wb){var f=b.ab,g=b.$a,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Yc?b.v.Rc:performance.now()/1E3}
self.pd=class{constructor(b,a,c){this.v=b;this.P=a;this.na=c;this.Sb=Tb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.wb=!1;this.ab=[0,0,0];this.$a=[0,0,0];this.ta=[0,0,0];this.da=null;this.Yb=!1;this.fd=0;this.I=!0;this.Y=this.ua=this.J=!1;this.Na=1;this.wa=!1;this.la=1;b=this.v.jd;this.Yc=1===b&&!this.Da()||2===b;this.Xa=this.ra=-1;this.ee=!1}l(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}ea(){return Kb(this.v,0<this.na.length?this.na[0]:"")}vc(){return this.P.vc()}kb(){return this.P.kb()}sc(){return this.P.sc()}Da(){return this.P.Da()}O(){}qc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Pa(){}fa(){return this.P.fa()}Play(){}Ea(){}nb(){}Lb(){}Ra(b){-1!==this.Xa&&b>=this.Xa&&(this.Xa=-1,this.ee&&this.Ea(),Ob(this.v,"fade-ended",this.na,this.Sb))}wc(){const b=this.Na;return isFinite(b)?b:0}Kb(){return this.v.Kb()}Rb(){}zc(){}Ha(){}yc(){}Ac(){}xc(){}jb(){var b=
this.Sb,a=this.na,c=this.fa(),d=-1===this.Xa?this.Na:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.ab,orient:this.$a,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ra}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Pa(),playbackRate:this.la,uid:this.ra,bufferOriginalUrl:this.vc(),bufferUrl:"",bufferType:this.sc(),isMusic:this.Da(),isLooping:this.Y,isMuted:this.wa,resumePosition:this.xc(),pan:f,stereoPan:this.da?
this.fd:null}}Gc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ha());Qb(this,b.isMuted)}};"use strict";
self.xe=class extends self.pd{constructor(b,a,c){super(b,a,c);this.P.Db.connect(this.G);this.P.onended=()=>this.Ic()}l(){this.Ea();this.P.Db.disconnect();super.l()}W(){return this.P.W()}Ic(){this.I=!0;this.ra=-1;Ob(this.v,"ended",this.na,this.Sb)}O(){return this.W().ended}qc(){return this.I?!0:this.O()}Pa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.wa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.kb()}' to position '${c}': `,e)}this.v.Fa(d);this.J=this.I=!1;this.Y=b;this.la=1}Ea(){const b=this.W();b.paused||b.pause();this.v.Qa(b);this.I=!0;this.J=!1;this.ra=-1}nb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.Qa(b);this.J=!0}}Lb(){!this.J||this.I||this.O()||(this.v.Fa(this.W()),this.J=!1)}Rb(){this.W().muted=this.wa||this.Kb()}zc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ha(){let b=this.la;this.Yc&&(b*=this.v.lc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}yc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}xc(){return this.Pa()}Ac(b){b?this.IsPlaying()?(this.W().pause(),this.ua=!0):this.ua=!1:this.ua&&(this.v.Fa(this.W()),this.ua=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.pb=null}
self.ze=class extends self.pd{constructor(b,a,c){super(b,a,c);this.s=null;this.cc=d=>this.Ic(d);this.Sc=!0;this.pb=null;this.S=this.ec=this.hc=0;this.bd=1}l(){this.Ea();W(this);this.cc=null;super.l()}Ic(b){this.J||this.ua||b.target!==this.pb||(this.I=this.Sc=!0,this.ra=-1,W(this),Ob(this.v,"ended",this.na,this.Sb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Sc}qc(){return!this.s||this.I?!0:this.O()}Pa(){let b;b=this.J?this.S:this.ec+(V(this)-this.hc)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.wa=!1;this.bd=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.pb=this.s;this.s.onended=this.cc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Sc=!1;this.Y=b;this.la=1;this.hc=V(this);this.ec=c}Ea(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.ra=-1}nb(){this.J||this.I||this.O()||(this.S=this.Pa(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Lb(){!this.J||this.I||this.O()||(W(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.pb=this.s,this.s.onended=this.cc,this.s.loop=this.Y,U(this,this.Na),this.Ha(),this.s.start(0,this.S),this.hc=V(this),this.ec=this.S,this.J=!1)}wc(){return super.wc()*this.bd}Rb(){this.bd=this.wa||this.Kb()?0:1;U(this,this.Na)}zc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ha(){let b=this.la;this.Yc&&(b*=this.v.lc);this.s&&(this.s.playbackRate.value=b)}yc(b){this.I||this.O()||(this.J?this.S=b:(this.nb(),
this.S=b,this.Lb()))}xc(){return this.S}Ac(b){b?this.IsPlaying()?(this.ua=!0,this.S=this.Pa(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.ua=!1:this.ua&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.pb=this.s,this.s.onended=this.cc,this.s.loop=this.Y,U(this,this.Na),this.Ha(),this.s.start(0,this.S),this.hc=V(this),this.ec=this.S,this.ua=!1)}Gc(b){super.Gc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.v=b;this.g=b.V();this.Td=-1;this.T=this.gd="";this.o=null}l(){this.g=null}N(){}U(){}jb(){return{type:this.T,tag:this.gd,params:this.o}}}
self.pe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}l(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ne=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Bb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.ub=X(this);this.ub.gain.value=c;this.A.connect(this.Bb);this.A.connect(this.h);this.Bb.connect(this.i);this.Bb.connect(this.X);this.X.connect(this.ub);this.ub.connect(this.Bb)}l(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Bb.disconnect();
this.X.disconnect();this.ub.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.ib.sd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);Y(this,this.ub.gain,e(a),c,d);break;case 5:this.o[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.me=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Jd=this.Id="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.tb=this.g.createConvolver();this.tb.normalize=c;this.tb.buffer=a;this.A.connect(this.tb);this.A.connect(this.h);this.tb.connect(this.i)}l(){this.A.disconnect();this.tb.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}jb(){const b=super.jb();b.bufferOriginalUrl=this.Id;b.bufferUrl="";b.bufferType=this.Jd;return b}};
self.qe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.vb=X(this);this.vb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.vb);this.vb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.vb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,Y(this,this.vb.gain,a/100,c,d)}}};
self.se=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.re=class extends Z{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=X(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.ib.sd;switch(b){case 4:this.o[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.ue=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,Y(this,this.m.pan,a,c,d)}}};
self.ve=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.te=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Gb=X(this);this.Gb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Gb.gain);this.C.start(0);this.A.connect(this.Gb);this.A.connect(this.h);this.Gb.connect(this.i)}l(){this.C.stop(0);this.C.disconnect();this.Gb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.oe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=X(this);this.jc=X(this);this.ic=X(this);b=d;.01>b&&(b=.01);this.jc.gain.value=b;this.ic.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.mc=this.g.createWaveShaper();this.Oc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Oc[32768+e]=f,this.Oc[32768-
e-1]=-f;this.mc.curve=this.Oc;this.A.connect(this.jc);this.A.connect(this.h);this.jc.connect(this.mc);this.mc.connect(this.ic);this.ic.connect(this.i)}l(){this.A.disconnect();this.jc.disconnect();this.mc.disconnect();this.ic.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.le=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.ke=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.Pd=new Float32Array(this.m.frequencyBinCount);this.de=new Uint8Array(a);this.be=this.bb=0;b=this.v;b.Ta.add(this);T(b)}l(){this.v.Ta.delete(this);this.m.disconnect();super.l()}Ra(){this.m.getFloatFrequencyData(this.Pd);this.m.getByteTimeDomainData(this.de);const b=this.m.fftSize;let a=this.bb=0;for(var c=0;c<b;++c){let d=(this.de[c]-
128)/128;0>d&&(d=-d);this.bb<d&&(this.bb=d);a+=d*d}c=self.ib.Ge;this.bb=c(this.bb);this.be=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};"use strict";async function Ub(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}
self.pa.Oa(class extends self.Ca{constructor(b){super(b,"localstorage");v(this,[["init",()=>this.Nb()],["request-persistent",()=>Ub()]])}async Nb(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});
